### ISSUE TITLE
The episode thumbnails are shown on unwatched episodes but I configured kodi not to

### ISSUE THREAD

**Issue by Paco8** [CastagnaIT/plugin.video.netflix#1059]
#### Your Environment
- Netflix add-on version: 1.13.1 using Kodi 19
- Operating system version/name:  Windows 10
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [x] Windows

### Describe the bug

I configured kodi to not show thumbnails for episodes I haven't watched yet to prevent spoilers, but the addon shows anyway.

#### Expected behavior

The thumbnails shouldn't be shown if kodi is configured to not show thumbnails for unwatched episodes.

#### Actual behavior

The thumbnails are shown.

#### Steps to reproduce the behavior

1.  Go to Kodi settings, media, videos, select the option "show information for unwatched items", disable episode thumb.
2. In the netflix addon navigate to an unwatched episode. The thumbnail for the episode is displayed but it shouldn't.

### Debug log

The debug log can be found here:

https://paste.kodi.tv/umaxezakom.kodi

#### Other information

This problem doesn't happen on Kodi 18.

**Comment by CastagnaIT** [comment]
![immagine](https://user-images.githubusercontent.com/3257156/106380219-fb831d80-63b0-11eb-94a0-f563c41b8a89.png)
As said the header these are settings for **Kodi library** not for the Add-ons,
usually if an add-on supports these settings, it is only because a workaround has been used,
and requires an extra development and maintenance

there only one specified option here that this add-on support,
is the setting "Flatten TV show seasons" and exclusively with `never` or `If only one season` setting,
but in the future also this will be removed and moved within the add-on settings for coherence.
