### ISSUE TITLE
Login from account link

### ISSUE THREAD

**Issue by gjroots** [CastagnaIT/plugin.video.netflix#1100]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
Hai developper I found one way to by pass login in netflix .. It needs two devices like 
1. android phone already login in app ..
2. Pc
3. Both devices connected in same network

 

#### Development tips
Removed...

**Comment by jayasatish** [comment]
## Feature request
I'm submitting a proposal to ...
  - [ ] ADD THIS STEPS TO LOG IN

### Describe your request
Hai developper I found one way to by pass login in netflix .. It needs two devices like 
1. android phone already login in app ..
2. Pc
3. Both devices connected in same network

 




#### Development tips
STEP .1
     Open  netflix app and in menu click on the ACCOUNT 
    
THEN IT WILL REDIRECT TO BROWSER WITH LOAD PAYMENT STUFF

STEP ..2
copy the url in browser 

STEP...3 

THEN transfer the url in CHROME BROWSER IN **PC**

THEN CLICK ON THE  NETFLIX LOGO 

SO it can opens  the http://netflix/browser 

Due to both devices connected to same network *netflix dont ask login credentials ....

So login will bypassd ..... without  any error .....

So this way  check one  develop this type step 
 



### Additional details or screenshots (if appropriate)

#### Specific details
i tested in all devices in same method it works without problem ....

**Comment by jakermx** [comment]
Hello,

This Addon does not look for hacking options or methods, this addon implements and add the feature to play NF Content on KODI Media Player, an what you are saying is pretty hard to  reproduce, caus, there are certificates, cookies, session ids, and some other stuff that handle the session, the only and  oretty strange way to do  what you are saying is having an connectionless proxy for ssl , with a DNS spoof and a content manager.

All encrypted data received from NF, needs some unique information per device to be decrypted.

Yes, it is possible what you are asking for , but pretty expensive and so unestable,...so why would be the real reasson to bypass it?  Maybe you  are looking for hijacking user sessions from a public hotspot, so  NO
Please respect NF, @CastagnaIT  and the whole community bro.... being open source doesnt means being out of the law, and dont play that way

Regards

**Comment by jakermx** [comment]
Please excuse me for answer, but your request is pretty offensive based on the hard effort that all the people that have had the time and discipline to bring NF features to a pretty nice plattform,  for FREE....

**Comment by jayasatish** [comment]
Thank you for replay ... I can understand but ... means nathing is  hacking.  the link  genated by  your account contains cokies also it wot work for all meens ... 
The netflix also have that feature say u activate account by connect to same network ...

I thing miss understand my saying ..  means i am hacking ..

Same method used to login Authentication key method it  accepts and genarate autho key .... 
I couldent  enter any credential in Authentication key software you created
Just copy my link and past in chrome url in your software 

It generats my autho key ....

So this way i am just proposing the method to without getting error  in during login in more devices ....
Like incorrect password ..

But i can under stand  but thank you for replaying ....

I have some basic  code knowledge and ha**ng skils if have any help contact me .... i contribute your work

**Comment by jayasatish** [comment]
> Hello,
> 
> This Addon does not look for hacking options or methods, this addon implements and add the feature to play NF Content on KODI Media Player, an what you are saying is pretty hard to reproduce, caus, there are certificates, cookies, session ids, and some other stuff that handle the session, the only and oretty strange way to do what you are saying is having an connectionless proxy for ssl , with a DNS spoof and a content manager.
> 
> All encrypted data received from NF, needs some unique information per device to be decrypted.
> 
> Yes, it is possible what you are asking for , but pretty expensive and so unestable,...so why would be the real reasson to bypass it? Maybe you are looking for hijacking user sessions from a public hotspot, so NO
> Please respect NF, @CastagnaIT and the whole community bro.... being open source doesnt means being out of the law, and dont play that way
> 
> Regards

Nothing you have to invest .... 
But thank you

**Comment by CastagnaIT** [comment]
@jakermx thanks for the warnings but this is not a real hacking

basically the netflix android app generate a token for the access, should be similar on how it is accessed through the new Smart TVs
which provides access by exchanging a code and tokens with a smartphone ("Activate a device" menu)

i think the best way is integrate the access by using the "Activate a device" menu from the netflix account
I'd rather try investing time on this instead of try adding others login workarounds

but @jayasatish the regular login user/pw is not working for you on the last addon version?

**Comment by jayasatish** [comment]
Thaks for understanding i hope to see this  in feature updates🤩🤩

**Comment by gjroots** [comment]
> @jakermx thanks for the warnings but this is not a real hacking
> 
> basically the netflix android app generate a token for the access, should be similar on how it is accessed through the new Smart TVs
> which provides access by exchanging a code and tokens with a smartphone ("Activate a device" menu)
> 
> i think the best way is integrate the access by using the "Activate a device" menu from the netflix account
> I'd rather try investing time on this instead of try adding others login workarounds
> 
> but @jayasatish the regular login user/pw is not working for you on the last addon version?
> 
> I will keep the Issue for possible future reconsideration

@ -- regular login user/pw is not working for you on the last addon version?

It works but some time NF BOT will lock down our accounts so thats reason o explain this method maybe works for you develop

**Comment by CastagnaIT** [comment]
@jakermx there is roku netflix source code browsable somewhere?

**Comment by CastagnaIT** [comment]
Information has been collected in the project section for the future

**Comment by jakermx** [comment]
> @jakermx there is roku netflix source code browsable somewhere?

not for public, but as I have done some Channels for Roku, I got access for a few low level channels, and grab somenice ones.. xD

but.... they main backhole could be grab from any spotify code....since basically both are based on the same protocols and content struct.

As Led Zeppellin song said....the song remains the same, ;)
