### ISSUE TITLE
Exception: HTTPError

### ISSUE THREAD

**Issue by dannyc211** [CastagnaIT/plugin.video.netflix#112]
*I'm submitting a ...*
  - [X] bug report
  - [ ] feature request
  - [ ] support request

## General information
Just Updated to lateted 14.5 version. Everything was working fine except my previously exported content. Started to export content again and worked fine for the first show. Ever since I cannot get back into the add on. I sign in to the point where you select which Netflix user but then get the Exception: HTTPError.  Any help would be greatly appreciated 
### Addon version used

[0.14.5]

### Description

Can’t login after the select user screen.

### Steps to Reproduce

1. [Open addon]
2. [Select which Netflix user you want to use]
3. [Error cannot progress]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [X] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [X] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by dannyc211** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/3317274/kodi.log)

**Comment by jakermx** [comment]
The issue is here

13:32:06.547 T:24812   ERROR: [plugin.video.netflix (7)] IPC call path_request returned HTTPError: 403 Client Error: Forbidden for url: https://www.netflix.com/api/shakti/vc42e0db4/pathEvaluator?materialize=false&withSize=false&drmSystem=widevine

try open it on your browser without being loggedin netflix page,  It should show Invalid User Tag, thenlogin into Netflix, and try again, it should response back something, but empty since you are accesing from another build id, but if you got Error 403, something else is wrong....I think it is related with th e models serverDef change, because the pathEvaluator uses info got from models response.

Share yoyr results pls

**Comment by dannyc211** [comment]
It turns out I was blocked from logging into Netflix on all my devices for some reason. After about an hour everything started working again including the plugin. Thank you so much for your response!

**Comment by Smeulf** [comment]
Thanks for the feedback.

It can happen sometime, and there's nothing to do but wait until it's unlocked.

We're trying to determine the root cause of that issue to avoid it at maximum, bit for now it's still very obscure.

I have the feeling it happens mostly when you log-in multiple times consecutively, but I can't confirm it yet.

**Comment by jakermx** [comment]
Check if yoy have static ESN on your settings.xml, if you use your
credentials on dynamic ESN config, Netflic blocks the account after 10
difent esn logins per hour

**Comment by Smeulf** [comment]
> Check if yoy have static ESN on your settings.xml

Well it seems fixed. There's a value that did not change since yesterday despite multiple restarts.
I tend to think this is not the cause of the issue. I'm not using any proxy or VPN either.
