### ISSUE TITLE
OSMC - KODI 19 Full MSL error information - 1044

### ISSUE THREAD

**Issue by xLudomanx** [CastagnaIT/plugin.video.netflix#1147]
#### Your Environment
- Netflix add-on version: 1.15
- Operating system version/name: OSMC KODI 19
- Device model:  Raspberry Pi 4 B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug
Don't play videos. I can login netflix, find a movie, but error ocour in play

#### Steps to reproduce the behavior

1.
2.
3.

### Debug log
https://paste.kodi.tv/aqohasasak.kodi

The debug log can be found here:

**Comment by NotherGithubAccount** [comment]
+1

Same problem on ODroid N2+ with CoreELEC 19.1-Matrix_nightly_20210503

The UI froze while watching Netflix. Rebooted, applied CoreELEC updates, now see the same issue as described by OP. I blamed the CoreELEC update, but maybe Netflix changed something?

**Comment by CastagnaIT** [comment]
the debug log is without debug info
follow readme instruction and provide good one

**Comment by xLudomanx** [comment]
Sorry about that.. Here the new log file.
Thanks

https://paste.kodi.tv/ujepiyafey.kodi

**Comment by CastagnaIT** [comment]
please try perform wiki instructions:
[This title is not available to watch instantly](https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Errors%29#This-title-is-not-available-to-watch-instantly)

**Comment by xLudomanx** [comment]
I tried the instructions outlined:

"Try reinstall Widevine CDM:
Open add-on settings (by context menu on the add-on icon), then go to Expert page and choose InputStream Helper settings, a new window will be opened, then choose (Re) install Widevine CDM. "

And it hasn't worked yet.

I have a raspberry pi 3B that installed OSMC KODI 18.x and on this system netflix worked.

When I bought a raspberry pi 4B and installed OSMC KODI 19.x the netflix stopped working (OSMC is in testing version for the raspberry pi 4).

As an additional information, I don't know of help, this same error occurs when I try to access netflix on my smartphone, through the Chrome browser, activating the Chrome option to "view as Desktop".

My impression is that Netflix has some blocking so that third-party apps do not project on smart TVs.

**Comment by CastagnaIT** [comment]
> As an additional information, I don't know of help, this same error occurs when I try to access netflix on my smartphone, through the Chrome browser, activating the Chrome option to "view as Desktop".

this because you cannot use the web version on android

This error is currently obscure there are many causes that can hit this error e.g.:
could happen if you are using an hotspot/tethering connection with your device (where is running Kodi)
could happen with some models of android (not certificated) devices
could happen if you try use a VPN (not supported)
could happen if you limit video resolutions from account settings
...and other unknown cases...
but from the feedback I've had, not everyone has the same error behaviour,
some despite the examples of use cases described above, still manage to play videos

as wiki say there is no other know solutions
if you will find your cause leave a feedback
