### ISSUE TITLE
argument "cipherKeyId" for "Encrypt" must be a string, bytes or a bytearray

### ISSUE THREAD

**Issue by chrisnikol** [CastagnaIT/plugin.video.netflix#1185]
#### Your Environment
- Netflix add-on version: 1.16.0
- Operating system version/name: android 9 and android 10 (2 devices)
- Device model:  BeeLink GT King, Huwaei MediaPad M6

Used Operating system:
* [X ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
I authendicate my account with Netflix using the authendication key method but when i try to play anything the addon is just thrown the error argument "cipherKeyId" for "Encrypt" must be a string, bytes or a bytearray and not playing the video.
I dont know if this is because the GT King and the Huwaei MediapadM6 is not officially supported by NetFlix.
At my other devices like windows machine and nvidia shield pro is working as it should be.

#### Expected behavior
When the user press play to any video the video start to play.

#### Actual behavior
You press the play button and thrown an error

#### Steps to reproduce the behavior
1. Navigate to Netflix Catalogue
2. Choose a video
3. Press play

### Debug log

The debug log can be found here: https://paste.kodi.tv/dohenuyavo.kodi

**Comment by CastagnaIT** [comment]
in the attached log the addon debug log is disabled, 
then there is very little informations, follow github Readme instructions on how enable it

anyway i have a GSKing that is the same thing, and on fresh install is working (of course you can not playback under Android because Beelink is banned)

I don't know what happened to you
I think that deleting the addon completely and also user data when prompt should resolve

the log of the huawei is missing then i can not say nothing

**Comment by chrisnikol** [comment]
Thanks for your help by unistalling the addon and deleting the settings and installing the addon again at huwaei is working fine.
At GT king it show me another error "MSLError: This title is not available to watch instantly. Please try another title"

But this is not the same problem As i read there isnt a lot that can be done about this error.

Anyway the debug log from this error is here https://paste.kodi.tv/ewocaqivep.kodi

**Comment by CastagnaIT** [comment]
yes for GTKing there are no solutions on android because is banned
the only way is use CoreELEC (dualboot)
