### ISSUE TITLE
Emtpy item lists except for movies 

### ISSUE THREAD

**Issue by Spliff58** [CastagnaIT/plugin.video.netflix#1196]
#### Your Environment
- Netflix add-on version: 1.12.5, already happened with 1.12.4
- Operating system version/name: Libreelec 9.2.7 Widevine
- Device model:  Raspberry PI4

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [x] Raspberry-Pi
* [ ] Windows

### Describe the bug

Since yesterday all item lists in the netflix addon are empty, except for movies.
Example: My list in the preview window shows my favorite series, but when opening the my series item I only get the two dots to return.
This is true for any list item except movies
#### Expected behavior

I would like to see a listing
#### Actual behavior

No listing at all (except for movie)
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found here:

https://paste.kodi.tv/ayefodawif.kodi
#### Screenshots

Screenshots are available here https://dccehome2.dnshome.de/s/6Qs97fDg7bncdnD

**Comment by CastagnaIT** [comment]
usually problems like this could be due to:
- Some type of filter set to the skin view (sidebar menu) that hide the items, in this case remove all filters set to the skin
- Is used a VPN or Proxy that cause wrong results, in this case remove it and reboot
- Corrupted addon cache due to possible http problem, in this case reboot the device

**Comment by Spliff58** [comment]
Thanks for the reply.
Action point one (filter on the skin) was the culprit and resetting solved the problem.
