### ISSUE TITLE
Replacing HTML Entities in the subtitles

### ISSUE THREAD

**Issue by marcoss9** [CastagnaIT/plugin.video.netflix#120]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

## General information
Some HTML Entities show in the subtitles.

### Addon version used

14.5

### Description

When I play some TV shows like "Suits" season one episode one instead of getting `&` in the subtitle line at 23:13 i get `&amp;`, and the same thing happens in "The Good Wife" season one episode one at 05:06, this problem in the Greek subtitles.

### Steps to Reproduce

1. Play the first episode from season one of "Suits"

**Expected behavior:** At 23:13 we should get `&` in the subtitle line

**Actual behavior:** We get `&amp;`

### Installation

* [x] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

Kodi 18.3 RC, Windows 10

## Debug log

SIMPLE RULES:
- Before performing any operation enable Kodi debug logging [Settings->System->Logging->Enable debug logging] only after perform the operations to reproduce the issue
- Copy here a link to your debug log, use something like [https://paste.kodi.tv/](https://paste.kodi.tv/) or similar
- Do NOT paste the content of the log here
- Do NOT cut the log
- If the log file is really huge (more than 1Mb) then in Kodi settings disable the *Component-specific logging*

## Other information

This page may help with the right replacement

https://www.w3schools.com/html/html_entities.asp

### Screenshots

![1](https://user-images.githubusercontent.com/52233859/60296391-4c55a900-9926-11e9-884a-9c9912b53aaa.png)

![2](https://user-images.githubusercontent.com/52233859/60308919-7f5e6380-994b-11e9-8be3-210fa2357377.png)

**Comment by jakermx** [comment]
it happens when you have subtitles in a Language and  then talk something in  other one, so special chars make a mess while parsing the subtitles...

sometimes, the special chars includes a end tag for css, html or xml 

i think that what you are talking about is about having a subtitle formatter that catch this things and when happens, remove this chars before display them. I dont know if this thing depends on the netflix client itself or a subtitle parser or os (becuase it depends on specific lang available charset).

It happens on windows, roku and linux neflix native clients, so good question.

**Comment by CastagnaIT** [comment]
no screenshots, no examples, no language specified
a request in this way you could avoid opening the issue...

our system is a little different from amazon addon, you can't do copy paste like you think
and our subtitle file type is different

**Comment by Smeulf** [comment]
@CastagnaIT is it not more an InputStream issue anyway?

**Comment by marcoss9** [comment]
@CastagnaIT Sorry, I updated the post, i was referring to the right replacement when i posted the Amazon addon code.

**Comment by jakermx** [comment]
based on the manifest

   {
      'type': 'timedtext',
      'trackType': 'PRIMARY',
      'rawTrackType': 'subtitles',
      'id': '6e6f6e657c554e4b4e4f574e7c756e6b6e6f776e7c66616c73657c656c7c5375627469746c65737c756e6b6e6f776e7c546578747c7072696d6172797c7c7c6e6f6e65',
      'new_track_id': 'T:1:0;1;el;0;0;',
      'isForcedNarrative': False,
      'isNoneTrack': False,
      'language': 'el',
      'languageDescription': 'Greek',
      'isLanguageLeftToRight': True,
      'downloadableIds': {
        'webvtt-lssdh-ios8': '697726021'
      },
      'ttDownloadables': {
        'webvtt-lssdh-ios8': {
          'size': 345560,
          'hashValue': 'iJjp9ewH9lAxx0J+LrZO7I+aL/w=',
          'hashAlgo': 'sha1',
          'isImage': False,
          'textKey': None,
          'downloadUrls': {
            '14668': 'https://ipv4-c182-dfw001-ix.1.oca.nflxvideo.net/?o=AQGyXo0SVQ7rrMgQgfGvMGmwlcflmy1z9qSJc6CLPH1q0W3LPmtJeqA8mzaxFOg7hklWWUzG27_dYUOVHr5dwqcm-zC6HxBQH_c6pf7Z9tRZGDn6JVH5ucrQg4egatq5zvUGmNLCgiExAPdg-NBKa0w9cw&v=3&e=1561730621&t=drrg9ZZqLeOEKprkR3zojmLZf0k',
            '18756': 'https://ipv4-c205-atl001-ix.1.oca.nflxvideo.net/?o=AQGyXo0SVQ7rrMgQgfGvMGmwlcflmy1z9qSJc6CLPH1q0W3LPmtJeqA8mzaxFOg7hklWWUzG27_dYUOVHr5dwqcm-zC6HxBQH_c6pf7Z9tRZGDn6JVH5ucrQg4egatq5zvUGmNLCgiExAPdg-NBKa0w9cw&v=3&e=1561730621&t=ReZm2Ic21L9S63HKvM15vaYKkLQ',
            '59200': 'https://ipv4-c346-dfw001-ix.1.oca.nflxvideo.net/?o=AQGyXo0SVQ7rrMgQgfGvMGmwlcflmy1z9qSJc6CLPH1q0W3LPmtJeqA8mzaxFOg7hklWWUzG27_dYUOVHr5dwqcm-zC6HxBQH_c6pf7Z9tRZGDn6JVH5ucrQg4egatq5zvUGmNLCgiExAPdg-NBKa0w9cw&v=3&e=1561730621&t=ZYOXvNzddFGI_F0BWNPRNjvnGbo'
          }
        }
      },
      'cdnlist': [
        {
          'id': 59200,
          'key': '6-11888-high',
          'lowgrade': False,
          'name': 'c346.dfw001.ix.nflxvideo.net',
          'rank': 9,
          'type': 'OPEN_CONNECT_APPLIANCE'
        },
        {
          'id': 14668,
          'key': '6-11888-high',
          'lowgrade': False,
          'name': 'c182.dfw001.ix.nflxvideo.net',
          'rank': 10,
          'type': 'OPEN_CONNECT_APPLIANCE'
        },
        {
          'id': 18756,
          'key': '7-11888-high',
          'lowgrade': False,
          'name': 'c205.atl001.ix.nflxvideo.net',
          'rank': 12,
          'type': 'OPEN_CONNECT_APPLIANCE'
        }
      ]
    },



this is what you got.... the source comes a &amp;, so it should be just " &, " so basically, your request is to  spoof the receikve subs into a HTML Entity Free, removing these:


Character | Entity | Decimal | Hex | Rendering in Your Browser
-- | -- | -- | -- | --

quotation mark = APL quote | &quot; | &#34; | &#x22; | " | " | "
ampersand | &amp; | &#38; | &#x26; | & | & | &
less-than sign | &lt; | &#60; | &#x3C; | < | < | <
greater-than sign | &gt; | &#62; | &#x3E; | > | > | >
Latin capital ligature OE | &OElig; | &#338; | &#x152; | Œ | Œ | Œ
Latin small ligature oe | &oelig; | &#339; | &#x153; | œ | œ | œ
Latin capital letter S with caron | &Scaron; | &#352; | &#x160; | Š | Š | Š
Latin small letter s with caron | &scaron; | &#353; | &#x161; | š | š | š
Latin capital letter Y with diaeresis | &Yuml; | &#376; | &#x178; | Ÿ | Ÿ | Ÿ
modifier letter circumflex accent | &circ; | &#710; | &#x2C6; | ˆ | ˆ | ˆ
small tilde | &tilde; | &#732; | &#x2DC; | ˜ | ˜ | ˜
en space | &ensp; | &#8194; | &#x2002; |   |   |  
em space | &emsp; | &#8195; | &#x2003; |   |   |  
thin space | &thinsp; | &#8201; | &#x2009; |   |   |  
zero width non-joiner | &zwnj; | &#8204; | &#x200C; | ‌ | ‌ | ‌
zero width joiner | &zwj; | &#8205; | &#x200D; | ‍ | ‍ | ‍
left-to-right mark | &lrm; | &#8206; | &#x200E; | ‎ | ‎ | ‎
right-to-left mark | &rlm; | &#8207; | &#x200F; | ‏ | ‏ | ‏
en dash | &ndash; | &#8211; | &#x2013; | – | – | –
em dash | &mdash; | &#8212; | &#x2014; | — | — | —
left single quotation mark | &lsquo; | &#8216; | &#x2018; | ‘ | ‘ | ‘
right single quotation mark | &rsquo; | &#8217; | &#x2019; | ’ | ’ | ’
single low-9 quotation mark | &sbquo; | &#8218; | &#x201A; | ‚ | ‚ | ‚
left double quotation mark | &ldquo; | &#8220; | &#x201C; | “ | “ | “
right double quotation mark | &rdquo; | &#8221; | &#x201D; | ” | ” | ”
double low-9 quotation mark | &bdquo; | &#8222; | &#x201E; | „ | „ | „
dagger | &dagger; | &#8224; | &#x2020; | † | † | †
double dagger | &Dagger; | &#8225; | &#x2021; | ‡ | ‡ | ‡
per mille sign | &permil; | &#8240; | &#x2030; | ‰ | ‰ | ‰
single left-pointing angle quotation mark | &lsaquo; | &#8249; | &#x2039; | ‹ | ‹ | ‹
single right-pointing angle quotation mark | &rsaquo; | &#8250; | &#x203A; | › | › | ›
euro sign | &euro; | &#8364; | &#x20AC; | € | € | €




Character | Entity | Decimal | Hex | Rendering in Your Browser
-- | -- | -- | -- | --

quotation mark = APL quote | &quot; | &#34; | &#x22; | " | " | "
ampersand | &amp; | &#38; | &#x26; | & | & | &
less-than sign | &lt; | &#60; | &#x3C; | < | < | <
greater-than sign | &gt; | &#62; | &#x3E; | > | > | >
Latin capital ligature OE | &OElig; | &#338; | &#x152; | Œ | Œ | Œ
Latin small ligature oe | &oelig; | &#339; | &#x153; | œ | œ | œ
Latin capital letter S with caron | &Scaron; | &#352; | &#x160; | Š | Š | Š
Latin small letter s with caron | &scaron; | &#353; | &#x161; | š | š | š
Latin capital letter Y with diaeresis | &Yuml; | &#376; | &#x178; | Ÿ | Ÿ | Ÿ
modifier letter circumflex accent | &circ; | &#710; | &#x2C6; | ˆ | ˆ | ˆ
small tilde | &tilde; | &#732; | &#x2DC; | ˜ | ˜ | ˜
en space | &ensp; | &#8194; | &#x2002; |   |   |  
em space | &emsp; | &#8195; | &#x2003; |   |   |  
thin space | &thinsp; | &#8201; | &#x2009; |   |   |  
zero width non-joiner | &zwnj; | &#8204; | &#x200C; | ‌ | ‌ | ‌
zero width joiner | &zwj; | &#8205; | &#x200D; | ‍ | ‍ | ‍
left-to-right mark | &lrm; | &#8206; | &#x200E; | ‎ | ‎ | ‎
right-to-left mark | &rlm; | &#8207; | &#x200F; | ‏ | ‏ | ‏
en dash | &ndash; | &#8211; | &#x2013; | – | – | –
em dash | &mdash; | &#8212; | &#x2014; | — | — | —
left single quotation mark | &lsquo; | &#8216; | &#x2018; | ‘ | ‘ | ‘
right single quotation mark | &rsquo; | &#8217; | &#x2019; | ’ | ’ | ’
single low-9 quotation mark | &sbquo; | &#8218; | &#x201A; | ‚ | ‚ | ‚
left double quotation mark | &ldquo; | &#8220; | &#x201C; | “ | “ | “
right double quotation mark | &rdquo; | &#8221; | &#x201D; | ” | ” | ”
double low-9 quotation mark | &bdquo; | &#8222; | &#x201E; | „ | „ | „
dagger | &dagger; | &#8224; | &#x2020; | † | † | †
double dagger | &Dagger; | &#8225; | &#x2021; | ‡ | ‡ | ‡
per mille sign | &permil; | &#8240; | &#x2030; | ‰ | ‰ | ‰
single left-pointing angle quotation mark | &lsaquo; | &#8249; | &#x2039; | ‹ | ‹ | ‹
single right-pointing angle quotation mark | &rsaquo; | &#8250; | &#x203A; | › | › | ›
euro sign | &euro; | &#8364; | &#x20AC; | € | € | €

I think it is not netflix addon related, but since the arch is >3 layers, the proxy could parse an suppress that overhead.

**Comment by Smeulf** [comment]
> the proxy

@jakermx what are you referring as 'the proxy'?

**Comment by jakermx** [comment]
Almost all AddOns in Kodi have an architecture that have a middleware, so FrontEnd  app just passes the request to it broker, in this case the proxy, and the proxy handle and verify the request before sending it to the backend server. this way the user experience is softly and frendly...some thing like mqqt model.

**Comment by Smeulf** [comment]
If I'm correct, to play a video what we basically do is 'just' to tell InputStream what sources to use. Then InputStream deals with the different stream sources to decode them before the player do it's job. There's a VebVTT parser inside InputStream.

The main problem is that WebVTT standard should not include any HTML entities from what I could read.

So either we change the subs before sending them to InputStream (witch will require a lot of processing) or InputStream can deal with those HTML entities, but for now they don't seems to care about that issue...

**Comment by marcoss9** [comment]
In "Settings", "Expert", turning on "Disable WebVTT subtitle support" fixed the problem of the HTML entities with the subtitles in Greek language for me.
