### ISSUE TITLE
NFAuthenticationKey doesn't work or I do something wrong, I can't generate NFAuthentication file.key

### ISSUE THREAD

**Issue by Mckarthur** [CastagnaIT/plugin.video.netflix#1230]
## Bug report
Good Morning,
Thank you first for all your work and help in advance.
I got stuck when "Logging in with authentication key". I have tried to generate the key following the instructions, on the one hand through Windows, with the file NFAuthenticationKey_Windows.zip, I execute it, I click on "start", it opens the Chrome browser incognito, and in the Netflix website "start session" I enter my email and password "which I have previously registered in Netflix", and then the page stays in "complete subscription", I don't do anything else, but there it stays, I wait and wait and the page does not close or anything, nor it also does not download any + pin files, and I think there is something I am doing wrong or something is currently down.
The same thing happens to me on Linux, I run the NFAuthentication.py file, open Chrome and load the Netflix page, enter my username and password and log in, and it stays on "complete subscription".
Could you help me please. Tell me if there is something I am doing wrong and how is the correct way to do it.
Thanks and sorry for bothering.
Greetings.

#### Your Environment
- Netflix add-on version: Netflix download Luar for Android TV box
- Operating system version/name: Probed in Windows 10 and Imac (Linux) too.
- Device model:  Netflix in YOU IN android tvbox

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x ] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ x ] Windows

### Describe the bug
1.- After logging in and waiting a few seconds, I receive this message when the browser closes automatically.
Please can you check this problem, to try to make it possible to watch NETFLIX I thank you very much!

#### Expected behavior
Sorry, I couldn't give you the records as this topic is not from the kodi player!

#### Actual behavior
Because of this, I can't go any further to get the authentication key in Kodi Player in android tvbox

#### Steps to reproduce the behavior
Nothing long after logging in, I get the same error.
Due to which I can't get the pin and NFAuthentication file.key as well.
All I get is the browser's temporary data folder

#### Possible fix
Sorry, I'm not a developer, so I'm so sorry, but I can help make videos and other things when needed.

### Debug log

The debug log can be found here:

**Comment by Mckarthur11** [comment]
I beg you to attend my request and remove the label of "Ignored rules" because I believe I have followed the template for the report of the problem that I currently have.
Thank you.
I await your reply with a possible solution.

**Comment by Mckarthur11** [comment]
![IMG_0163](https://user-images.githubusercontent.com/90683515/133407347-1e2cedb5-1ed9-47f2-96ac-2c986d9b0aaa.JPG)
![IMG_0164](https://user-images.githubusercontent.com/90683515/133407365-386e4f67-8b45-4fa8-b72d-e1cd6ed9057a.JPG)
![IMG_0165](https://user-images.githubusercontent.com/90683515/133407376-3f746df6-527a-44ec-a303-191f692e5abb.JPG)
![IMG_0166](https://user-images.githubusercontent.com/90683515/133407383-ed65497a-af58-49bd-8464-a18717ece0a0.JPG)

I attach photos of the tests carried out on Mac and when the screen does not close, I close the chrome browser, because otherwise at the time it closes itself. And on the other hand, I have also tried with Windows and once I have entered the username and password, I press start session and it does not do anything.
I'm waiting for you to tell me something, please. I've tried it about 20 times, both on Mac and Windows, and I don't get the NFAuthentication.key file!

**Comment by CastagnaIT** [comment]
from what i see in your screenshot of website in background
you are not logged in the netflix website in the webbrowser
or you have not activated your account

when you login to the netflix website usually appears the profiles list page

**Comment by CastagnaIT** [comment]
closed due to inactivity
