### ISSUE TITLE
Viewing netflix in kodi when subscribed to the "Mobile" plan

### ISSUE THREAD

**Issue by nitinjs** [CastagnaIT/plugin.video.netflix#1232]
## Feature request
I'm submitting a proposal to ...
  - [] new feature
  - [*] change an existing feature

### Describe your request
I get an error when I try to play netflix video in kodi as I am subscribed to the "Mobile" plan,
How to view netflix in kodi when subscribed to the "Mobile" plan??

#### Describe the use case
It should play even if I am subscribed to mobile plan

#### Development tips
Can you allow option to "Always show mobile version of video"?

#### Specific details
I get following error when I try to open a netflix video in kodi

#### Screenshots
![image](https://user-images.githubusercontent.com/298479/133781031-a1c5483d-cfb7-49c1-bdeb-2c0328081746.png)

**Comment by CastagnaIT** [comment]
currently "mobile" plan is limited to some countried only
it will be difficult that it will work because this addon is based on website, not mobile API
also it is not clear on which operating system you are using kodi

even if somehow hacked way maybe possible to play the videos, would be limited to smartphone only
it is a very limiting accont, suggest you to change account plan

**Comment by nitinjs** [comment]
Can you tell more details about how to change[hack] then addon to play the videos?
I just want to change the HD stream to mobile stream and install the addon
