### ISSUE TITLE
Cannot Load Cryptodome.Hash

### ISSUE THREAD

**Issue by Nadonate** [CastagnaIT/plugin.video.netflix#1234]
#### Your Environment
- Netflix add-on version: **1.17.0 Matrix**
- Operating system version/name:  **Pop OS (Debian) 21.04**
- Device model:  N/A

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug

App won't start, throws error:

**OSError: Cannot load native module 'Cryptodome.Hash._MD5'**

Additionally, cannot log-out in settings

#### Expected behavior

App should start

#### Actual behavior

App doesn't start, broken

#### Steps to reproduce the behavior

1. Open Kodi
2. Start Netflix App
3.

#### Possible fix

Seems a path is missing, related to PyCrypto?

### Debug log

The debug log can be found here:

[https://pastebin.com/yNBDFKeJ](https://pastebin.com/yNBDFKeJ)

#### Other information

N/A

#### Screenshots

N/A

**Comment by Nadonate** [comment]
The required libraries were present. The issue ended-up being inputstream-adaptive. A kodi reinstall fixed my issue.

Thanks

**Comment by t-morales** [comment]
I was having a similar problem after a ubuntu upgrade. I am writing it here because I think it is related although this issue is closed. @CastagnaIT if you think that it would be worth giving more details or opening a new issue, I could do it

After an ubuntu upgrade I was having similar problem with Cryptodome.Hash, something like:
OSError: Cannot load native module 'Cryptodome.Hash._MD5': Trying '_MD5.cpython-38-x86_64-linux-gnu.so'
I tried installing the library pycryptodomex as said in the wiki but it was present and updated.
After a closer look in the error I saw that it was not finding the following file:
/usr/lib/python3/dist-packages/Cryptodome/Util/../Hash/_MD5.cpython-38-x86_64-linux-gnu.so
What I had in that folder was:
/usr/lib/python3/dist-packages/Cryptodome/Util/../Hash/_MD5.cpython-39-x86_64-linux-gnu.so
So it seems that it was looking for version 38 while I had version 39. No idea why or where that is defined. I assume something did not get updated properly.
So what I did is a symbolic link from 39 to 38.
After that and some try and error process I had to do similar links for several 39 versions files to 38, in particular in the folders:
/usr/lib/python3/dist-packages/Cryptodome/Util/../Util/
/usr/lib/python3/dist-packages/Cryptodome/Util/../Cipher/
/usr/lib/python3/dist-packages/Cryptodome/Util/../Protocol/

I know it is doing things the hard way and probably there is a better and easy way, but this worked for me and I can use the addon.
