### ISSUE TITLE
Default Viewtype

### ISSUE THREAD

**Issue by CraigHB** [CastagnaIT/plugin.video.netflix#131]
I'm submitting a feature request

## General information

Netflix has a lot of pages and the addon-on often goes to the default viewtype instead of the one selected at the top of the category or first page viewed.  When changing viewtypes often the add-on does not remember the last selected.

### Addon version used

0.14.6

### Steps to Reproduce

Select a list or category with several pages
Change the viewtype
Notice subsequent pages use the default viewtype for the Kodi skin.

**Expected behavior:**

When a viewtype is selected for a category or initial page of a multi-page list it should remember the viewtype and make it sticky for subsequent pages or subcategories.  Alternately, there should be a settings selection for viewtype at the global level

**Actual behavior:** 

The add-on does not remember user selected viewtype through multiple pages or subcategories.  A selection does not stick to sub-categories or secondary pages.

### Installation

I'm using this Netflix Repo

### Operating System

Linux aarch

#### Additional informatin on the environment

CoreELEC 9.0.3 on Odroid-N2
Using Estuary skin

**Comment by CastagnaIT** [comment]
this does not depend on the plugin,
the management of the skins is the skins themselves
the behavior that saves the last position is managed by the skin you currently use

In the case of Estuary Kodi skin:
this has several limitations, one this is what you are specifying, because it saves the settings per page not for the menu you access,
and even if you set to View folder a custom id, from the last test i had done long ago the estuary skin don't supports other types of views for this type of page

you can always try other skins, some have the function to block view types
but i warn you that some skins could create malfunctions in the addon
the only way is to try and find the most suitable one

**Comment by CraigHB** [comment]
I figured that might be the case, but if there's any way to control it from the add-on it was worth a try to request it.  Anyway, that seems like a big oversight in the skin design to me, maybe there's a way to get in there at the coding level and change the skin's default viewtype.

**Comment by CastagnaIT** [comment]
I have not found a way, the only possible way would be to encode the type of view via code,
but this is a very very bad pratice, that would only be compatible with one type of skin
so in any case if you find a solution update me thanks
