### ISSUE TITLE
Play from URL funktion

### ISSUE THREAD

**Issue by sonnenwind** [CastagnaIT/plugin.video.netflix#1325]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request

Dear CastagnaIT,

I’m not sure if this is the right or appropriate place for this question:
If I have a Netflix share link url in the form of
https://www.netflix.com/us/title/xxxxxxx?s=i&trkid=yyyyyyy&vlang=en&clip=zzzzzzz
is it possible to interact with your add-on (by the means of a python script) and make it play the stream using the xxx, yyy, or zzz numbers , respectively?

I hope that I didn’t overlook this function on the documentation and therefore asking a very dumb question ;)

Thank you for this great add-on!

#### Describe the use case

I was thinking to write a small Pythonista script that would allow me to select a movie on my phone’s Netflix app and then play it on Kodi using the “share-run Pythonista script” functionality to extract the link.

**Comment by CastagnaIT** [comment]
the addon not support weblinks,
mentioned link provide the tvshowid or the movieid only

since there is already a lot of complex things to keep maintained, i will add new things only due to website changes or for particular cases that will be evaluated

but if you are able you can create a your addon that elaborate the link and callback this addon to the play endpoint:

with the movieid you can use it to play movies, by calling:
`plugin://plugin.video.netflix/play/movie/MOVIEID/`

instead for the tvshow if you are able to get the full id's then you can play by calling:
`plugin://plugin.video.netflix/play/show/TVSHOWID/season/SEASONID/episode/EPISODEID/`
the tvshowid alone is useless

(replace uppercase with appropriate id's)

**Comment by sonnenwind** [comment]
Thanks for your reply! I’ll try your suggestion.
