### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by Artiom-M** [CastagnaIT/plugin.video.netflix#1332]
### Netflix add-on version

plugin.video.netflix v1.12.9

### Operative systems used

LibreELEC

### Kodi version used

Kodi 18 (Leia)

### Description of the bug

When trying to play a movie it shows an  error
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 58437: ordinal not in range(128)`

### Steps to reproduce the behavior

1. Navigate to a film
2. Press play

### Debug log - mandatory

https://paste.kodi.tv/uwigaroguz.kodi

### Additional context

I've reinstalled the plugin an re-logged into the netflix. Still have the error

**Comment by sanchosk** [comment]
I have the same problem :( Same setup - RPi 4 running kodi 18, same Netflix add-on.
I tried logout and login, switching profiles, etc. Nothing helps.

**Comment by DerGanjalf** [comment]
This is definitely not related to the Netflix plugin, but to the InputStream helper. 
https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/495
There is a fix since 14 days and they also released a new version containing this fix two days ago, but it's not in the Kodi Repo yet. You can apply the fix by DokuroKM in the comments on your own or wait for the new InputStreamHelper version to release in the repo

**Comment by Artiom-M** [comment]
Yes, the fix for InputStreamHelper works! Thank you.
