### ISSUE TITLE
Addon crashes kodi on quick menu changes

### ISSUE THREAD

**Issue by cuh7b5** [CastagnaIT/plugin.video.netflix#1338]
### Netflix add-on version

1.18.4+Marix.1

### Operative systems used

Linux (Ubuntu / Mint / ...)

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

In some situations the Netflix addon crashes Kodi. One way to reproduce the error is:
1. Click on any menu entry within the Netflix addon (e.g. "Continue Watching")
2. After the previous step instatnly go back to the main menu (i.e. pressing "'ESC").
Result: Kodi crashes without any reasonable log output.

I use Arch Linux.

### Debug log - mandatory

https://paste.kodi.tv/uyekuvekod.kodi

**Comment by CastagnaIT** [comment]
i dont think that i can help much if kodi crashes cannot be fixed by addon,
and i need full information to try understand what happens
1) full debug log as explained in README, the provided one is cutted and without info
2) provide stacktrace error via gdb, i know that this works on ubuntu should be similar on arch:
- open terminal / install gdb
- `gdb /usr/lib/x86_64-linux-gnu/kodi/kodi.bin`
- a gdb shell should be opened with a text like `Reading symbols from...`
- now open kodi
- make it crash
- Return on the shell in terminal and type: `bt full`
- attach the stacktrace output

**Comment by cuh7b5** [comment]
Unfortunately I could not get any gdb trace out of kodi. Here are the logs:

[Kodi crashlog](https://paste.kodi.tv/icicamupaf.kodi)
[gdb output](https://paste.kodi.tv/zotatajixa)

**Comment by cuh7b5** [comment]
I was just guessing that python was causing the problem.

Now I tried downgrading package python 3.10.3-1 => 3.10.2-1. And it works, I cannot reproduce the issue with this python version.

I would file a bug at python but I have no clue where to start. Should I paste my kodi crashlog to them?

**Comment by CastagnaIT** [comment]
I had some suspicions and this confirmed
i have already heard of several bugs on 3.10 versions but different nature
you can do as you think best
i don't have time to follow these things also on python core
