### ISSUE TITLE
Feature Request: Multiple profile watched status

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#135]
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## General information

When watching a video, Kodi uses the path of the video to save the watched status.

When multiple profiles in Netflix exists, whatever the profile used, the path is the same for the video, IE plugin://plugin.video.netflix/play/show/80161848/season/80161849/episode/80162147/

So if I watch a video before my wife, in her Netflix profile it will be marked as watched too.

I propose we add the profile_id at the end of the video path to ensure Kodi remembers it , like in  plugin://plugin.video.netflix/play/show/80161848/season/80161849/episode/80162147/?profile_id=ZZZZZZZZZZZ

So for Kodi, the same video started from differents profiles will be threated as different videos (tested with a fake profile_id parameter)

The main problem with this way is that all watched status will be lost when enabling this option for existing installation. But that would be a real benefit for new ones.

Plus we don't have yet an easy way to retreive the active profile id (?). Could be passed with parameters all along, or maby easily saved in the persistent storage.

**Comment by jakermx** [comment]
One way to try it, would be using kodi profiles and force autologin on Netflix, sojust one Kodi  user will be using the netflix profile, so context and namespaces will be separated.

**Comment by Smeulf** [comment]
Sure using different Kodi profiles and autologin can solve the issue as it can be configured to use multiple databases (I do use the MySQL setup).

But that's very less easy to use than just opening the add-on and select the Netflix profile...

Plus in Leia there's a lot of issues with profiles.

My point is if we allow not using autologin (as I like it), there's must be a way to determine the profile that watched the video. Or we have to enforce autologin, and that will require most people to create Kodi profiles, maybe just for the Netflix 'Kids' profile.

**Comment by CastagnaIT** [comment]
I believe many will complain if we force them to use kodi profiles,
I also thought of adding the profile id
but as you have seen there is this boring problem...lose all watched items it's a b#ll br##k
that's why i avoided this change, but it would be useful

I have an idea on how this function could be added in a painless way
I'll give you an example on a branch

**Comment by Smeulf** [comment]
> I'll give you an example on a branch

Ready to test !

**Comment by Smeulf** [comment]
> lose all watched items it's a b#ll br##k

That's why I thought to have it disabled by default in settings, and enable it at first run for new install.

I really wonder how you can implement it without breaking the current watched status, as it's stored in the Kodi db :/

**Comment by CastagnaIT** [comment]
painlessly but not without free from defects...
this system can be useful as a transitional step with the future addon releases.

To work you need to publish the two commits at a distance of time and release number
we have to give users time to update the addon, in order to save version number and start the transition.

this system works for a limited range of releases, not all, all future releases that exceed the range, in new installations use the new system.
So the option setting to use the old system remains configurable by the user anyway.

in the distant future all this should be removed, at the cost of breaking the few users who still use the old implementation

https://github.com/CastagnaIT/plugin.video.netflix/commits/exp_library_profiles

**Comment by Smeulf** [comment]
Kind of version checker. That would be useful also for future releases indeed.

Also, what about a warning message at first run of the new version? So we can warn users upgrading the add-on there's a breaking change, and give them choice to enable it or not?

**Comment by CastagnaIT** [comment]
Yes it can be done, of course only for the version transition

**Comment by Smeulf** [comment]
As a side note, if we implement this, we may think about the library too.

Who is watching from the library? How do we handle multiple profiles for stream continuity, etc... Not so easy as we could think.

**Comment by CastagnaIT** [comment]
I think this thing is practicable only inside the addon,
not from the kodi library.
In kodi library the best way is create multiple kodi profiles that separate the database data
