### ISSUE TITLE
KODI 19 - Playback error "MSLError: Email or password is incorrect"

### ISSUE THREAD

**Issue by pegonma** [CastagnaIT/plugin.video.netflix#1381]
### Netflix add-on version

1.18.8+matrix

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Even though I am using Login with Authentication key (which seems to work fine: I am successfully logged in), when I try to play a video I get the error

"MSLError: Email or password is incorrect"

After this, I am logged out and the addon asks me again to log in. If I do and try again to play a video, I get the same error.

### Debug log - mandatory

https://paste.kodi.tv/bimuxezujo.kodi

**Comment by CastagnaIT** [comment]
Kodi 18 uses obsolete components 
therefore if it is not something that is changing in the website in these days nothing can be done
i no longer provide support for Kodi 18

So only advice is to wait to see if it is a generalized problem due to the website
or use Kodi 19

**Comment by pegonma** [comment]
OK, thanks! I didn't realize LibreElec 10 was available for RPI2-3 since March, so I can now upgrade to Kodi 19.

**Comment by pegonma** [comment]
Okay I just updated to Kodi Matrix and I got the exact same behavior with version 1.18.8+matrix.

**Comment by pegonma** [comment]
I did Logout and logged back in, didn't work.

I logged out, changed my password and logged back in, that worked! So weird. Thanks anyway! I do not know if this is a bug with the addon or with Netflix though...

**Comment by CastagnaIT** [comment]
happy that you solved
fwik this can happens when you change password account and when website ask if you want to preserve login on all devices,
and you answer yes, in this case it may happen that the login expires early in the MSL api rather than in the api to get the data lists
but are uncommon exceptions

but if there are other use cases i don't know,
netflix does not release documentation on how their backend works
therefore we cannot know how handle each single situation
