### ISSUE TITLE
Profile Chooser at startup

### ISSUE THREAD

**Issue by 888iee** [CastagnaIT/plugin.video.netflix#1383]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
It would be nice to have a setting to enable choosing my netflix profile whenever I start watching something.
So Multiuser setup would be more easy

#### Describe the use case
I currently have a setup where I use kodi profiles to switch to user specific stuff, but this so slow and when you just want to watch a show you need to wait a lot longer before beginning to watch. When I could have just one kodi profile where my shows are laid out in on one screen and someone else's shows on another screen, it wouldn't matter who is there as the profile can be chosen after clicking on the show. Like I'm watching Breaking Bad S1E3 and someone else is watching Breaking Bad S2E1 the records wouldn't be changed on the wrong profile.

**Comment by CastagnaIT** [comment]
> When I could have just one kodi profile where my shows are laid out in on one screen and someone else's shows on another screen

this is not a proper way to use Kodi for multi-user purpose...
is not clear to me what means exacly with "on one screen"
but if you are talking of widgets, this addon dont support widgets ufficially and no support is provided for widgets,
as explained here: https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

if you are talking of regular browsing (by opening addon icon to be clear),
then you have to use the profile selection menu, is not possible browse lists with a specific netflix profile and play videos by using another netflix profile, this violates the way how the website works and also the addon,
making this type of mixture only leads to problems with browsing lists and playback

a kind of alternative solution is use Kodi library,
that is the only place where the addon allow to select a netflix profile every time you play a video.
To do this you have to export all video lists to Kodi library and/or enable library auto-sync (you can find some help on Wiki).
But due to its particular use this way leads to some disadvantages:
- its not possible sync videos watched status in a "two way" mode
- due to the forced selection of different profiles where play a video, playback problems/errors may be encountered

**Comment by 888iee** [comment]
Okay thank you for the clarification. Unfortunately my specific use case won't be possible like this.

If my feature request to create a setting which can be enabled to always ask on which profile to watch is also not possible then you can close this issue.
