### ISSUE TITLE
Kodi hangs then crashes after Netflix video stops or ends

### ISSUE THREAD

**Issue by go-vegan** [CastagnaIT/plugin.video.netflix#1407]
**Netflix add-on version**

1.18.9+matrix.1

**Operative systems used**

Ubuntu 22.04.01 LTS

**Kodi version used**

Kodi 19.4.0 (Matrix)

**Description of the bug**

A few seconds after stopping playing a Netflix video (any video), Kodi hangs for a couple of minutes and then crashes entirely.
It does not happen after watching non-Netflix video.

**Steps to reproduce the behavior**

1. Play a Netflix video
2. Stop the playback after a couple of minutes (or just let it finish by its own)
3. Within a few seconds Kodi will freeze and eventually crash

**Debug log**

https://privatebin.net/?3ffb05a8454c33f9#Ct8mWgxb5rD9x7P2ew49eXyoa813uuVxU9Lq2P9T7Fud

**Workaround**

I am able to exit Kodi gracefully _during_ the Netflix playback (e.g. not stopping it first).
Then I can start Kodi again.

**Additional context**

The problem started only a few weeks ago.

**Comment by CastagnaIT** [comment]
Tested on same Ubuntu version with a fresh install and i dont have crashes

from the log the addon has already finished his operations before the crash
so the crash appears to be due to other things not related to this addon
in any case Kodi crashes cannot be solved by this addon

suggest you as first step to reinstall Kodi from scratch by deleting also Kodi user data
if crashes still occurs you have to ask for help in to Kodi channels

**Comment by Jusix** [comment]
I suffer from the same issue.
