### ISSUE TITLE
Addon "background services" affects other addons

### ISSUE THREAD

**Issue by Piklis** [CastagnaIT/plugin.video.netflix#1477]
### Netflix add-on version

1.19.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

Hello, I have a problem that is not the fault of this addon, but caused by it.

I need to figure out, what "netflix background services" are started when kodi starts, because it's probably affecting another addon.

I have addon "streamcinema" installed, and another addon "titulky.com". But this "titulky.com" addon stop working, when Netflix addon is installed and enabled. I think "background services" somehow affects these "titulky.com" addon, by I really don't how. 

Is there any possibility to help me? I can give logs and cooperation as needed.

Thank you for your helpfulness.

### Debug log - mandatory

https://paste.kodi.tv/rofuqokugi.kodi

**Comment by CastagnaIT** [comment]
i need to see the titulky addon sources to understand something where a link?

with netflix addon we dont use fixed ports on service so we pick the first free port,
if not already done titulky service should implement something similar

but the error

> RecursionError: maximum recursion depth exceeded while calling a Python object

means that your titulky service code or "plugin.video.stream-cinema-2-release" code is running an endless operation,
then since never end the client raise "socket.timeout: The read operation timed out"

the first to check is why your service have an infinite looped operation?

**Comment by Piklis** [comment]
So there is problem with titulky addon? For example because trying to use fixed port, which is not free?

Addon source is https://github.com/beam-kodi-addons-repository/service.subtitles.titulky.com

**Comment by CastagnaIT** [comment]
i dont know titulky or plugin.video.stream-cinema-2-release addons,
my are only suggestions by looking your log

service.subtitles.titulky.com and plugin.video.stream-cinema-2-release addons are in some way linked? i have no idea

but as i said before the error RecursionError from plugin.video.stream-cinema-2-release addon suggest a code loop with no exit
need to be investigated on plugin.video.stream-cinema-2-release addon

if you are not the developer of these addons you have to report this to relative maintainers

**Comment by Piklis** [comment]
Thank you for your help, I'm just a user who has a problem with addons, and I can't find a solution. I tried to contact developer of service.subtitles.titulky.com, but he keeps telling me "its addon only establishes a connection to the server, but it failed" and he doesn't want to deal with it anymore. So I write to you, trying to move on... 

So I don't know what to do :-)

Plugin.video.stream-cinema-2-release is addon, which playing videos (movies) from servers, it works standalone, and work well with plugin.video.netflix.

Service.subtitle.titulky.com is addon used with stream-cinema-2 and it's only automaticly (or manually) download subtitles to movies which are currently being played. This work fine, but when there is plugin.video.netflix installed (and enabled) it stop working. Service.subtitle.titulky.com cannot "establishes connection" and doesn't download any subtitles. When plugin.video.netflix addon is disabled (or enabled but logged off) it works fine. But it wasn't always like that, couple of months ago (not sure when) all three addons working together fine.

I just want things to work, but I don't know who to turn to.

**Comment by CastagnaIT** [comment]
since the main error come from plugin.video.stream-cinema-2-release addon
you should report to plugin.video.stream-cinema-2-release addon maintainer

i mentioned TCP port problem because is the only thing that could affect another TCP server
so two services with same port == conflicts
there is nothing else

just for info, the TCPServer used on this addon it is a standard python TCPServer bound to a free port found at service starts
https://github.com/CastagnaIT/plugin.video.netflix/blob/master/resources/lib/run_service.py#L31
this has never changed for years

**Comment by CastagnaIT** [comment]
i close issue since i have no idea what i could do
if plugin.video.stream-cinema-2-release dev have some type of suggestions
you can however let me know here

**Comment by Piklis** [comment]
Thanks for now, I'll let you know if I have more information
