### ISSUE TITLE
Netflix plugin won't play any titles after using "Sign out of all devices" on Netflix website

### ISSUE THREAD

**Issue by waynethomas69** [CastagnaIT/plugin.video.netflix#1488]
### Netflix add-on version

1.20.0+matrix.1

### Operative systems used

LibreELEC

### Kodi version used

Kodi 19 (Matrix)

### Description of the bug

I recently had to use the "Sign out of all devices" feature on the Netflix website. Now I am unable to play any titles on my libreelec systems with the following error:
`MSLError: User must login again`

I have logged out of the Netflix plugin (successfully) and then logged back in multiple times. I have rebooted, and even changed my Netflix password, however the plugin continues to produce that error.

### Steps to reproduce the behavior

1. Open the Netflix plugin
2. Select any user profile
3. Select any video

### Debug log - mandatory

https://paste.kodi.tv/yoquxalabe.kodi

**Comment by CastagnaIT** [comment]
after the login, what steps you have done to login again on the addon?

**Comment by waynethomas69** [comment]
I have tried multiple methods. In every case I used the "logout" inside the configuration settings and waited until it notified that the log out was successful. I logged in using the username and password (successfully) multiple time. In some instance I rebooted libreelec, and sometimes I also tried reinstalling the plugin. I also used the authentication method but the results were the same.
I also deleted ~/.kodi/userdata/addon_data/plugin.video.netflix/msl_data.json however the issue persisted even after a reboot. I did notice that the file wasn't re-generated while testing last night.

I should point out the issue has resolved itself after leaving they system idle overnight. I checked, and msl_data.json was re-generated when I tested it this morning. It might be completely unrelated, but it is interesting that it didn't regenerate last night when I was having the issue.

**Comment by CastagnaIT** [comment]
msl_data.json has no influence in your case

when you do the "logout" from addon all account info are deleted
the only info kept should be the ESN, i will try reproduce and see if change something remove or kept it

I know that "Sign out of all devices" of website require some time to be completed, this may have caused some confusion

**Comment by eXt73** [comment]
Hi, it's been the same for me for about a week. First, the MSLError error appeared and information that the content is currently not available = it starts to play and after about 30-40 seconds it freezes the image - the sound still works. Logging out and back in doesn't help = using key [password error when logging in via email]. After a successful login, trying to play anything results in an error: MSLError: User must login again

**Comment by pr3dL** [comment]
I have exactly the same behavior as eXt73, ending in a "User must login again" loop. The reinstallation from the plugin and widevine was also withour success.

**Comment by CastagnaIT** [comment]
i tested again "Sign out of all devices" website influence on addon
found that something has changed with recent website changes
and without going on too many details some other side effects and also errors can happens

i have tried to better manage it, you can try with this test:
[plugin.video.netflix_1.20.3+matrix.1_20230112_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/10400916/plugin.video.netflix_1.20.3%2Bmatrix.1_20230112_t1.zip)

when you do "Sign out of all devices" from website you need to wait at least 5/10 minutes before generate a new Auth Key (or however relogin), otherwise you will get "MSL User must login again", looks like MSL on website server has not yet changed a kind of previous state, i have no idea, however waiting mentioned minutes fix it automatically
