### ISSUE TITLE
Multiple sign-in to the Netflix add-on

### ISSUE THREAD

**Issue by etgecata** [CastagnaIT/plugin.video.netflix#1562]
### Netflix add-on version

v1.20.8

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Sorry for the bad english. I use Kodi mostly because of the Netflix addon. I have the following problem. I use widgets with which I have set up shortcuts to different sections of the Netflix add-on. Almost every time I login to Kodi when loading the widgets, Neflix logs in 2-3 times. I also get new device is using your account emails. I get 10-15 emails a day depending on how many times I log into Kodi.
This problem is with ARCTIC HORIZON 2 skins, Titan BINGIE MOD, I have also tried with Estuary ModV2 skin.
I am using Nvidia shield pro 2019

I am asking for help and assistance.

### Debug log - mandatory

https://paste.kodi.tv/oqekunomeq.kodi

### Screenshots

![Netflix](https://user-images.githubusercontent.com/17301428/223351653-35c1b8bd-9714-45a5-a509-79c70cef34fe.jpg)

**Comment by CastagnaIT** [comment]
this addon do not support Widgets because they force call the addon in uncontrollable manner
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#skin-widgets---problems-and-limits

i see more differents problems are happened along all widgets requests that are currently not possible to fix

one of these problems is that something wrong happened with login data that required a relogin,
and widgets has triggered multiple cascading times the addon with login attempts

the only thing i can suggest is remove all widgets
and completely uninstall the addon and his user data, then reinstall it from scratch
then instead of widgets use kodi library that is a lot more stable and safe
