### ISSUE TITLE
I have a stuttering problem for a long time and I can't find a solution

### ISSUE THREAD

**Issue by etgecata** [CastagnaIT/plugin.video.netflix#1592]
### Netflix add-on version

Netflix v1.22.0

### Operative systems used

Android

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

Hello. I have a stuttering problem for a long time and I can't find a solution. I've been following this thread for a long time. I've tried all the options and solutions from this thread as well as different versions of Kodi. I'm using Kodi, mostly to watch Netflix with the ARCTIC HORIZON 2 skin. I'm using a LAN cable. Nvidia Shield 2019. The movie I played and for which I have attached the log I have 7 interruptions. I would be very grateful if you could see the log I am attaching and help me.

### Debug log - mandatory

https://paste.kodi.tv/bevozijayi.kodi

**Comment by CastagnaIT** [comment]
unfurnately from addon side there is nothing that is possible to do
i have same android device, but atm i have no way to test 4k
so the only thing i can say is that at 1080p i have almost no stuttering they rarely happen but are very light

but stuttering is due to a problem on audio/video sync on nvidia firmware, kodi has currently included a workaround in the kodi core to alleviate this problem, but will be never full solved until nvidia fixes his firmware

no idea if ARCTIC HORIZON 2 skin can influence on this problem, i always use default kodi skin

my suggests that i can say are:
- try add/use this advanced setting mod: [advancedsettings.xml.txt](https://github.com/CastagnaIT/plugin.video.netflix/files/11645103/advancedsettings.xml.txt)
remove ".txt" extension before put the file in to "userdata" folder you need to use a kind of file manager app to access to kodi user folder
- try disable subtitles

**Comment by etgecata** [comment]
Thanks for your reply. I tried both suggestions. Unfortunately, there is no improvement.

**Comment by etgecata** [comment]
I have these dropouts certain specific videos (4K high bitrate streams of specific TV shows) happening on both Kodi 21 and Kodi 20.1

**Comment by etgecata** [comment]
The problem turned out to be in the Nvidia Shield. After I downgraded firmware to 8.2.3 I no longer have the interruptions and stuttering of the picture.

**Comment by etgecata** [comment]
I know about this problem before I upgraded to 8.2.3. I was using version ISA v21.1.0. That's not the reason. I have been struggling with this problem that I have described for several months. After upgrading to Nvidia Shield firmware 8.2.3, I no longer have any stuttering or stuttering.
