### ISSUE TITLE
netflix.zip vs 'repository.castagnaIT.2.0.0.zip. Which one should I choose? 

### ISSUE THREAD

**Issue by Lawiih101** [CastagnaIT/plugin.video.netflix#1630]
When I select 'Install from zip' in Kodi and choose the name assigned to your repo, I encounter two folders named 'Kodi 18' and 'Kodi 19', along with a zip file named 'repository.castagnaIT.2.0.0.zip'. Selecting this zip file in Kodi 19 prompts a message indicating it’s not compatible with this Kodi version. However, opening the 'Kodi 19' folder reveals several differently labeled zip files, ranging from '16.0.matrix.1.zip' to '22.3+matrix.1.zip'.

I am puzzled about the meaning behind these labels. Despite all being under the 'Kodi 19' category, could the labels '20.0+', '21.0+', and '22.+' imply compatibility with Kodi versions 20, 21, and 22, respectively?

Furthermore, under what circumstances should I opt for 'netflix.zip' over 'repository.castagnaIT.2.0.0.zip'?"

**Comment by CastagnaIT** [comment]
you have to use the repository repository.castagnaIT.2.0.0.zip if you want automatic updates
otherwise you choose the version you want e.g. 22.3+matrix.1.zip but you are responsable to check when a new addon version is released and so update manually the addon

> I am puzzled about the meaning behind these labels. Despite all being under the 'Kodi 19' category, could the labels '20.0+', '21.0+', and '22.+' imply compatibility with Kodi versions 20, 21, and 22, respectively?

folders are relative to Kodi addons API not the actual kodi version
then addon versions under "Kodi 19" are the same that are used for all kodi versions higher than 19, so there is no reason to create folders for each kodi version because use same files
