### ISSUE TITLE
"Browse subgenres" repeats endless in special cases

### ISSUE THREAD

**Issue by Falke-Design** [CastagnaIT/plugin.video.netflix#1665]
### Netflix add-on version

1.23.1

### Operative systems used

Android, Windows

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

At some point the "Browse subgenres" is endless:
"List of all Kinds" > "TV Shows" > "Browse subgenres" > "Sitcoms" > "Browse subgenres" > "US-Sitcoms" > "Browse subgenres" > "Emmy Sitcoms"
![kodi_subgenres_repeat](https://github.com/CastagnaIT/plugin.video.netflix/assets/19800037/81ee7fad-c776-4774-8b37-650d5236c905)

### Steps to reproduce the behavior

"List of all Kinds" > "TV Shows" > "Browse subgenres" > "Sitcoms" > "Browse subgenres" > "US-Sitcoms" > "Browse subgenres" > "Emmy Sitcoms"

### Debug log - mandatory

https://paste.kodi.tv/wajiwihigo.kodi

**Comment by CastagnaIT** [comment]
this is known behaviour since this is a custom menu access implementation that the website dont have
you could add a kind of limit count to limit subfolders browsing access but i think will make more chaos in an already jungle of code
or a new additional item should be added on top of the listitems to have an easy "go back to mainmenu screen"

I personally will not invest time on this, also given the many recent pplayback problems that are difficult to investigate and find a fix with my knownledge
