### ISSUE TITLE
Audio not synced with video

### ISSUE THREAD

**Issue by martusi61** [CastagnaIT/plugin.video.netflix#1679]
### Netflix add-on version

1.20.3

### Operative systems used

CoreELEC

### Kodi version used

Kodi 20 (Nexus)

### Description of the bug

My system is installed on a Tanix TX3 mini, in the past it had already given the same problem, which was then resolved on its own, but now it My system is installed on a Tanix TX3 mini, in the past it had already given the same problem, which was then resolved on its own, but now it has persisted for days and the difference between audio and video is much longer.Really annoying.sisted for days and the difference between audio and video is much longer.Really annoying.

### Debug log - mandatory

https://paste.kodi.tv/yuqutobota.kodi

**Comment by CastagnaIT** [comment]
unfurnately i have already investigated to this last year, but the problem was on android only and limited to specific hardware
after some months the problem is disappeared without do nothing
so i have not understand exactly where come the problem but its not addon dependent and no real solutions

you can try use "audio offset" on addon "playback" settings as workaround

**Comment by martusi61** [comment]
I had already seen the "audio offset" function, but it is not easily usable, furthermore the defect is also progressive, I don't think it is feasible. I'll do some tests. Thanks anyway and good work.

**Comment by martusi61** [comment]
I managed to solve the audio synchronization problem by lowering the resolution from 1080 to 720 by operating in the settings, I hope it helps you and everyone who has encountered my same problem.
