### ISSUE TITLE
Stefano  Gottardo

### ISSUE THREAD

**Issue by riccy123** [CastagnaIT/plugin.video.netflix#184]
I have already replied to your comment

OPEN YOUR MIND- don't close it

**Comment by Smeulf** [comment]
Do you think this is appropriate? Do you really think we will be willing to help you again after that?

Just please think about it before answering again!

And didn't I asked you NOT TO SCREAM???!!!

**Comment by CastagnaIT** [comment]
Forget it, some people are not worth 2 cents...
But if he thinks he will continue in this way i will take disciplinary action from github

**Comment by riccy123** [comment]
Let me explain my '2 cents'- without shouting:-)

Ah--- Kodi's VPN policy--

I understand Kodi has been in a very sensitive position re use of its software.
But its declaration that 'it doesn't need a VPN' is understandably political , and appears the chosen direction to avoid any scrutiny concerning its legitimacy.

They may just as well say  ''it doesn't need an internet connection'', because it  functions fine with local drives.

What it does, is leave people who use a VPN legitimately, in a position where the mere mention of a VPN appears to cause suspicion , and creates a situation where any discussion becomes quickly removed to 'off topic'', or the thread is subsequently closed- as has happened here and in a kodi thread.
I came to GitHUb in the hope I could raise my issue directly to the author, as the Kodi forums do not want to engage.
Although I understand you may not feel that way ( you may use one yourself), the possibility of raising a problem with that dreaded word mentioned, becomes almost impossible.

There was no offence intended, if it appeared that way , I apologise, and if you want to shut me off, thats fine as well.


respectfully

Keith

**Comment by CastagnaIT** [comment]
I don't know who told you those sentences and i'm not interested, there's a document with the basic rules described, a quick read is enough to avoid problems with the Kodi forum.

The VPN it's a complicated topic, it doesn't just depend on how a person uses it that can be legal or illegal (eg breaking geoblock), becouse in some countries VPN it is not legal, and some free VPNs are not totally secure becouse companies that offer free services they can profit extrapolating your data from the tunnel.

You may not even agree to Kodi rules, but you don't consider it in a broader view.

There is a great responsibility to the part of the Kodi organization, 
there is a specific reason why some topics are forbidden, two main:
-ones are respect to the other companies to which Kodi uses or offers services (with the help of addons) this to avoid being brought into legal cases that which can sue the entire organization and prohibit the software development.
-second do not violate the laws of the various countries of the world.

In my case, as current main mainteiner of Netflix addon,
i am in the position of being primarily responsible for legally using of the service offered by Netflix.
Netflix disallow VPN and i do not intend to be responsible for helping people to use it,
because if one day netflix sues someone for inappropriate use, that someone will be Kodi and myself.

**Comment by riccy123** [comment]
HI,
Thanks for replying.
Always good to hear your view.
I have to differ though- netflix do not disallow a VPN ( it is not encouraged) 
Its legality entirely depends on its use - like so many other things.

I wish you well with your work.
