### ISSUE TITLE
Add the Netflix add-on to the official Kodi repository

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#191]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
I don't know if this was ever proposed/discussed before, I surely could not find it here. But it would be nice if the Netflix add-on was part of the standard Kodi repository.

#### Describe the use case
So users find it in any Kodi installation, and existing users get updates without delay or manual effort.

#### Development tips
Simply send a PR to the leia branch of this repository and follow the rules.
https://github.com/xbmc/repo-plugins/tree/leia

**Comment by Smeulf** [comment]
I can speak only on my name, not @CastagnaIT one, but regarding the current status of the add-on, I'm not sure it's ready to join Kodi repos.

There's too many issues that need to be resolved, and too few mainteners at the moment for such a piece of code.

Plus it's not full Python V3 compatible, and may not follow all Kodi directives to be added.

On my name only again, I'd say 'later maybe'. But @CastagnaIT remains the boss here, so... ;)

**Comment by dagwieers** [comment]
Then maybe we should list all the things that are required for this to be ready, and we can share that work. I don't mind helping out with Python3 support as well as having an automated testing framework. We implemented this for two add-ons and a lot of that effort/experience can be applied here too.

**Comment by Smeulf** [comment]
For the record: https://kodi.wiki/view/Add-on_rules

**Comment by CastagnaIT** [comment]
others have already requested this type,
the addon follow almost all the rules, so because some need to be checked again

many changes have been made lately and with the implementation of python 3 coming up
we will have to change many parts of the code yet...
I don't think it's the right time for this

however, i have too little time to manage another repository

**Comment by dagwieers** [comment]
> however, i have too little time to manage another repository

I don't understand, why would you have to manage another repository?

**Comment by Smeulf** [comment]
To clarify, Kodi addon repo is managed by Kodi team.

When a new release is made, it's 'sufficient' to submit a PR to Kodi repo, and then they merge the commits.

The only repo to manage remains the original one. On Kodi add-ons it's just 'like' a fork.

**Comment by dagwieers** [comment]
@Smeulf This 'fork' is actually just copying over the newly released files (or even better the released ZIP content).

You can run `kodi-addon-checker . --branch=leia` to test the current master branch for hints and known issues with the current release.

I think we need to do the following things in this order:
- Modify the Makefile to include some new targets
  - sanity (pylint, tox)
  - kodi-addon
  - test (integration, unit)
  - zip (creates a ZIP file on the fly)
- Add automated integration tests using custom Kodi stub files
- Make all these tests work out fine
- Add Travis support and include above tests
  - Include testing for Python 2.7, Python 3.6 and Python 3.7
  - Fix all Python 3 issues that come out of these tests
  - Add secured credentials to master branch for testing
- Add Coverage support (codecov?) to ensure we are testing as much code paths as possible

**Comment by Smeulf** [comment]
That's a lot of stuff ^^

Before, we need IMO to fix the most annoying issues:
- https://github.com/CastagnaIT/plugin.video.netflix/issues/186 (in progress)
- https://github.com/CastagnaIT/plugin.video.netflix/issues/152
- https://github.com/CastagnaIT/plugin.video.netflix/issues/185
- https://github.com/CastagnaIT/plugin.video.netflix/issues/167 (if possible, right now we're stucked)

Then we have to clean up the code, and perform first sanity checks manually.
We're not currently using Pylint, I was about to ask if we should or not. So if @CastagnaIT agree, maybe we should use it instead of the basic PyCharm code inspections tool (that's an opened question).

However, even if we can't include the addon into the repo, everything you're suggesting would improve the addon quality, so it can worth the effort, should we have sufficient time.

I can deal with code inspection and cleanup, at least for a first pass.
But I can't deal with all the tools you're proposing to use, as I don't know them yet.

**Comment by dagwieers** [comment]
Known bugs should not keep us from pushing it to the Kodi repository IMO. Obviously it would be better to not have them, but a large user base also brings in people with skills to fix some of the things affecting them. So I wouldn't be too worried.

(We pin the issues with the highest impact/scope in the GitHub issues, so people can easily find them when they want to report them, sometimes more reports help to reproduce or pinpoint the cause as well.)

**Comment by dagwieers** [comment]
> That's a lot of stuff ^^

We are almost there. The Python3 stuff I would postpone until we have our integration tests working and we have added all possible code-paths. Only then will we know if changes to support Python 3 still work on Python 2 (and vice versa).

**Comment by dagwieers** [comment]
**Known kodi-addon-checker issues**
- Icon.png should be solid. It has transparency.
- Fanart should have either 1280x720 or 1920x1080 or 3840x2160 but it has 1600x900

**Comment by Smeulf** [comment]
I gonna try to change them. Fanart will be resized to 1920x1080.

**Comment by dagwieers** [comment]
So we are almost there, if the current PRs are merged, we can start fixing Python 3 issues.
And then enable the Python 3 support in Travis.

(I am going to remove the existing Python 3 stuff because I think we can do this better anyway).

Still on the TODO list is:
- Make use of **script.module.enum34** when it is available (xbmc/repo-scripts#1108)
- Either upgrade **script.module.myconnpy** or add our own **script.module.mysql-connector** add-on

**Comment by henry-nicolas** [comment]
Any reason this is closed? It would be easier for users to be able to install this add-on from the official kodi repo and it seems that the plugin has matured a lot over the last 2 years.

**Comment by CastagnaIT** [comment]
because of the lawsuit that was raised against one of the first developers of this addon by Netflix's lawyers,
the XBMC/Kodi Foundation does not assume responsibility for distributing this addon by using its platform,
If Netflix opens up a bit more to the opensource market in the future, maybe the situation will improve

**Comment by henry-nicolas** [comment]
Ah, that makes total sense, thanks for your quick feedback :-)

**Comment by npmstart-pray** [comment]
> because of the lawsuit that was raised against one of the first developers of this addon by Netflix's lawyers,
> 
> the XBMC/Kodi Foundation does not assume responsibility for distributing this addon by using its platform,
> 
> If Netflix opens up a bit more to the opensource market in the future, maybe the situation will improve

It all gets down to DRM - so unless the entire world agrees to fall under one legal and financial system, it's highly unlikely that this will ever happen.
