### ISSUE TITLE
Better integration with inputstreamhelper

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#205]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
As one of the developers of **script.module.inputstreamhelper**, we recently refactored this add-on so it is easier to integrate it in 3rd party add-ons for troubleshooting.

Things you could integrate from your Settings menu:
- An information pane showing Kodi, InputStream and Widevine versions
- Open the InputStream Helper settings
- (Re)install Widevine CDM from the menu (could help with issues)

#### Describe the use case
We cannot guarantee that Widevine CDM will work perfectly in the future. There have been cases in the past where a new Widevine release broke a perfectly working system, or caused performance issues on some platforms.

Giving people access to version information and control over their Widevine installation may help in troubleshooting or fixing playback issues.

That said, the ultimate goal of InputStream Helper is that it stays out of the way. And that is still the goal, so it is up to you whether you want to give more information/control to your users (when things stop working).

Also see:
- https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/API
- https://github.com/emilsvennesson/script.module.inputstreamhelper/wiki/Integration
- https://github.com/emilsvennesson/script.module.inputstreamhelper/issues

**Comment by Smeulf** [comment]
About the information pane I'm mixed: I do prefer logs rather than data writen by a user. A typo is not rare. To be honest, what may help a lot is if InputStream Helper shows the Widevine version in it's debug log. Seems at 0.4.2, it doesn't, only says it found the binary.

But I'm not against, even if we already have many tabs.

The "Reinstall Windevine" and "Open Inputstream Helper settings" can be really interesting.

**Comment by dagwieers** [comment]
> I do prefer logs rather than data written by a user.

The main reason for having this is that the user does not have to log on to the system to look at logs just to get the most basic information (e.g. to compare). And e.g. the Widevine version information is not available elsewhere.

**Comment by dagwieers** [comment]
That said, InputStream Helper does have an icon now on Kodi and the settings can be access through that icon. So it may be sufficient to document that in a troubleshooting section in the wiki of the add-on.

**Comment by Smeulf** [comment]
> InputStream Helper does have an icon now on Kodi

Here it's still 'just' a dependency, so I have to to system settings, addons, manage dependency to see it. Not very convinient. We do have a sortcut for InputStream settings, having one for InputStream Helper is not a big deal and indeed may be sufficient.

**Comment by dagwieers** [comment]
You should have version 0.4.2 by now? Unless you installed it yourself and auto-update is disabled. Could you check?

**Comment by Smeulf** [comment]
It is 4.0.2.

![ish-mainConfig](https://user-images.githubusercontent.com/1092948/64699448-13e55600-d4a5-11e9-9b9b-c1f6bb77eafd.png)

"Funny part": It's shown as a "Program Addon" but not in "My Addons/All", see below. That's why I didn't find it, cause I use to go to "My Addons" to see what I have.

![ish-ProgramAddons](https://user-images.githubusercontent.com/1092948/64699568-59a21e80-d4a5-11e9-98fe-19536d2882b7.png)
![ish-MyAddonsAll](https://user-images.githubusercontent.com/1092948/64699591-63c41d00-d4a5-11e9-808d-2522fd90d5f9.png)

Anyway, we still can add a shortcut for InputStream Helper settings :)

**Comment by Smeulf** [comment]
I have it in the addons home screen btw, didn't look at it previously.

**Comment by dagwieers** [comment]
Correct, this is something we have to document in our Wiki as well. (Thanks for reminding me)

Since it is a "script.module" it is not listed, except as a dependency. But it is already nice users can access the settings this way.

**Comment by dagwieers** [comment]
And I am going to reuse your screenshots in the documentation ;-)

**Comment by CastagnaIT** [comment]
interesting to next development, can be integrated i would prefer perhaps within the expert menu
since it is not a strictly essential but occasional thing
But first i would like to solve all the fire meat we have already opened

**Comment by dagwieers** [comment]
@CastagnaIT Adding this is a five minute job if we know what we want to add.
I just added this to another add-on (VTM GO) and I plan to add it to YouTube as well.

**Comment by CastagnaIT** [comment]
i think can be closed now this issue
