### ISSUE TITLE
Improving Kodi for Video-on-Demand plugins

### ISSUE THREAD

**Issue by dagwieers** [CastagnaIT/plugin.video.netflix#235]
## Help request

I made a list of things that IMO Kodi is lacking but would make life easier for Video-on-Demand plugins to create a better user experience.

I am sure @CastagnaIT and @Smeulf have some ideas/needs for the Netflix plugin that belongs in this thread as well: https://forum.kodi.tv/showthread.php?tid=348138

**Comment by CastagnaIT** [comment]
most of the things mentioned don't seem useful in netflix addon except for this:
- we add a ᵛ -marker to the "label" to indicate when a tvshow is being followed

others do not understand well what you want to integrate:
- "Continue watching list" ? where?
- Context menus for "Mark as watched" and "Mark as unwatched", or "Reset resume position" ?? at least in kodi library and in the list inside netflix addon is working, do you mean other things?

with netflix addon we rely on the website system, so for example geolock, it is already integrated by netflix...

but there is other important things to fix in Kodi:
- Support IETF BCP 47 to country/region iso code (eg. pt-BR, es-ES) with UI language/audio language/subtitle language, this is necessary to fix many language recognition errors, not only with netflix addon but also with Amazon addon.
- In reference to the above reason (support ISO IETF ...), have same IETF BCP iso with rpc "Player.GetProperties": "audiostreams" and "subtitles"
-In addition the Json-RPC  "Player.GetProperties": "subtitles"/"currentsubtitle" does not specify which are the forced subtitle tracks... this is a serious lack.
-Minor bug the xbmc.executebuiltin "AlarmClock" function, if only the value in seconds is passed, these are not respected becouse it seems to be multiplied by 60...?!? instead if you pass an HH:MM format is working as expected.
-Is missing the support to show flag/infolabel of hi-res audio example Atmos.. now i have used flag "Dolby-HD" in order to distinguish,
furthermore it is not possible to distinguish the HIRES tracks from normal audio tracks when you open the audio language selection menu, this is ugly.
-Another important thing is to add support to Kodi, to obtain from the OS the HDCP versions supported, this is important mostly for InputStream Adaptive, and consequently to Netflix addon to get the right hdcp streams for the system in use

**Comment by CastagnaIT** [comment]
> Well, since the VOD provider stores these resume points, we need to send the position to their service when the video is stopped. We can do this fine, however Kodi has context menus for "Mark as watched", "Mark as unwatched" and "Reset resume position", but we cannot intercept when the users uses these context menus, and hence we cannot update the resumepoints with the VOD provider.

Oh understand, so in the specific case of netflix the thing is even more complicated...
here the system to manage resume-point/watched with netflix server is missing, it is very difficult to implement, so to now it's okay that kodi handle these things

> Sure, but you have to make the visible to the user. And there is no infoLabel to store that information to be used by skins. So we have to add metadata information to the plot, whereas it would be nice if skins would show a nice Lock icon.

in our case the contents not allowed are not included in the lists,
i have not seen any kind of flag or anything similar in the data obtained

for the other things i already imagined that i have to make a new post,
but i should include more documentation

**Comment by dagwieers** [comment]
> Oh understand, so in the specific case of netflix the thing is even more complicated...
> here the system to manage resume-point/watched with netflix server is not implemented, it is very difficult to implement, so to now it's okay that kodi handle these things

Well, if you would have a working implementation you would hit the same problem. Although I noticed that you have cleared the context menu, because I don't see any of these items in Netflix. I guess we could do that as well, and add our own context items for this.
