### ISSUE TITLE
(Windows7) Unicode Decode Error - Beta23

### ISSUE THREAD

**Issue by mrkapqa** [CastagnaIT/plugin.video.netflix#29]
*I'm submitting a ...*
  - [ ] bug report
  - [ ] feature request
  - [x ] support request

## General information

Hello , i tried to install your latest release .0.23 but it would not enable the functionality on Kodi 18.2 Nightly running on Windows 7

### Addon version used

[eg. 13.21.0]

### Description

[Description of the bug or feature]

Error when clicking on installing Video-Add-On Netflix
"Unicode Decode Error"

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [ ] I'm using a different source (Please tell which)

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [ ] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

#### Additional informatin on the environment

[Descripe your environment a bit more detailed, are you using LibreElec f.e.]

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/) or [https://pastebin.com/](https://pastebin.com/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]

[You can erase any parts of this template not applicable to your Issue.]

**Comment by mrkapqa** [comment]
[kodi.log](https://github.com/CastagnaIT/plugin.video.netflix/files/2975411/kodi.log)

**Comment by CastagnaIT** [comment]
I can't trace the error, at least not directly in the netflix addon,
first of all it fails InputStream, and then crashes netflix addon.
I'll try to open an issue to InputStream addon, but don't know when it'll be fixed..

you only have one chance, right now you are using a windows user account whose name contains a special character, this creates problems with python system,
I'm not sure that it's enough to change the name of the windows user you're using because now the user's folders have been created with that name.

so in order to use netflix addon or in any case any other addon that uses InputStream, you have to create a new windows user with a name without special characters, and access to windows with that new account name to start kodi

**Comment by mrkapqa** [comment]
Hello , thank you very much for your help.

i had to reinstall Windows 7 because i was not able to change the Admin/Username Folder properly ... now it is functioning well . It was probably because of the Umlaut "ü" in "Büro" name as you suggested, with "Office" as username no such error.

Playback started with exiting Kodi one time and restarting it after having installed your plugin.
