### ISSUE TITLE
Subtitles sometimes not showing correctly; one line at bottom, 2nd line in middle of screen

### ISSUE THREAD

**Issue by dl16** [CastagnaIT/plugin.video.netflix#4]
*I'm submitting a ...*
  - [x] bug report
  - [ ] feature request
  - [ ] support request

### Addon version used
0.14.0~beta19

### Description
Subtitles often (but not always) show incorrectly.  If there are two successive sentences, first will show at bottom correctly while 2nd line shows simultaneously in middle of screen and shifted left.  

Using Aeon-Nox Slivo skin

### Steps to Reproduce

1. Play a Netflix show with subtitles enabled.  For example "American Crime Story: The People v. O.J. Simpson"

**Expected behavior:** 
subtitles show centered at bottom screen

**Actual behavior:** 
If there are two successive sentences, first will show at bottom correctly while 2nd line shows simultaneously in middle of screen and shifted left.  

## Context (Environment)
Windows 10, v18 Leia
Aeon-Nox Slivo skin

### Installation

* [ ] I'm using this Netflix Repo
* [ ] I'm using other Netflix Repo (Please specify which)
* [x] I'm using a different source (Please tell which)
CastagnaIT beta19 zip

### Operating System

* [ ] Linux (x86/x64)
* [ ] OSX (x86/x64)
* [x] Windows (x86/x64)
* [ ] Linux (ARM)
* [ ] Android

## Debug log

[Please include a link to your debug log (use something like [http://sprunge.us/](http://sprunge.us/) or [https://pastebin.com/](https://pastebin.com/)) or similar, please do not paste]

## Other information

[e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, etc.]

### Screenshots

[Please add a screenshot if that helps understanding your problem]
![subtitle shift example](https://user-images.githubusercontent.com/1995283/52534738-32b71a80-2d13-11e9-99ae-1f54da827b40.jpg)

[You can erase any parts of this template not applicable to your Issue.]

**Comment by CastagnaIT** [comment]
This is a problem of inputstream.adaptive not related to the netflix addon,
i'm trying to find out if they're going to correct

**Comment by dl16** [comment]
ok thanks, i see you opened issue here, i will keep an eye on it:
https://github.com/peak3d/inputstream.adaptive/issues/229

a few other issues there seem related:
https://github.com/peak3d/inputstream.adaptive/issues/221
https://github.com/peak3d/inputstream.adaptive/issues/214

i see on Kodi forums xiji had described this issue nicely as "like yoda speaks"
https://forum.kodi.tv/showthread.php?tid=329767&pid=2807079#pid2807079
then, essam315 suggested using a "0.13.21" based modified release, and i dont see whether or not it worked.

anyway, my understanding is 0.13.xx releases would not have nearly the features as these 0.14.xx betas.  when i tried 0.13.xx it didn't even play video.

**Comment by CastagnaIT** [comment]
version 13 is almost totally different from version 14 have little in common
I'll check the modified version to see if there's anything useful.

but I think the best way is fix inputstream.adaptive

**Comment by Essam315** [comment]
@dl16
Try using "simplesdh" profile instead of "webvtt-lssdh-ios8", open "profiles.py" in

C:\Users\Essam\AppData\Roaming\Kodi\addons\plugin.video.netflix\resources\lib\services\msl

and replace "webvtt-lssdh-ios8" with "simplesdh" (by the way i do not get this problem with "webvtt-lssdh-ios8" profile on my Windows 10, Kodi 18 Leia, default settings and skin, 1080p monitor, full screen).

**Comment by dl16** [comment]
i was on 720p, tested with 1080p and do not have this issue.  thanks for the tip.  haven't tested the "simplesdh" to see that would also fix for 720p

**Comment by CastagnaIT** [comment]
problem fixed, download again the addon,
i hope that in the future my request for a fix will be granted from peak3d

**Comment by Essam315** [comment]
@CastagnaIT
Changing the version in the comparison from 2.3.8 to 2.3.14 will disable the subtitles for many languages that are not supported in "simplesdh", and only supported in "webvtt-lssdh-ios8" like Japaneses, Chinese, Arabic, Hebrew, Korean and many more, if the installed inputstream.adaptive is less than 2.3.14, the reason for choosing 2.3.8 as the minimum inputsream.adpative version for using "webvtt-lssdh-ios8" was because 2.3.8 was the first version to support "webvtt-lssdh-ios8", and the reason for using "webvtt-lssdh-ios8" because all the languages are support in it (using "webvtt-lssdh-ios8" was my idea many thanks for "peak3d" for taking my request and supporting it in inputsream.adpative and in the Netflix plugin 0.13.XX and many thanks for "caphm" for taking my request and supporting it in the Netflix plugin 0.14.0).

This problem will occur only in the English subtitles because Netflix only use lines in the same time with different position on the screen with the English subtitles, the workaround may be something like enabling "simplesdh" and  "webvtt-lssdh-ios8" at the same time and only use "simplesdh" if only the subtitles are in English language or inputsream.adpative version is less then 2.3.8 (not sure if this is possible to work right or not).

**Comment by Essam315** [comment]
@CastagnaIT
Changing the version in the comparison from 2.3.8 to 2.3.14 will disable the subtitles for many languages that are not supported in "simplesdh", and only supported in "webvtt-lssdh-ios8" like Japaneses, Chinese, Arabic, Hebrew, Korean and many more, if the installed inputstream.adaptive is less than 2.3.14, the reason for choosing 2.3.8 as the minimum inputsream.adpative version for using "webvtt-lssdh-ios8" because 2.3.8 was the first version to support "webvtt-lssdh-ios8", and the reason for using "webvtt-lssdh-ios8" because all the languages are supported in it.

**Comment by Essam315** [comment]
@CastagnaIT
Changing the version in the comparison from 2.3.8 to 2.3.14 will disable the subtitles for many languages that are not supported in "simplesdh", and only supported in "webvtt-lssdh-ios8" like Japaneses, Chinese, Arabic, Hebrew, Korean and many more, if the installed inputstream.adaptive is less than 2.3.14, the reason for choosing 2.3.8 as the minimum inputsream.adpative version for using "webvtt-lssdh-ios8" was because 2.3.8 was the first version to support "webvtt-lssdh-ios8", and the reason for using "webvtt-lssdh-ios8" because all the languages are supported in it.

**Comment by CastagnaIT** [comment]
@dl16 awaiting correction i have opted for the addition of a new temporany option in the expert settings
to the next version enable "Disable WebVTT subtitle support".

**Comment by Essam315** [comment]
The last modification makes WebVTT subtitles disabled by default, changing from

`def _subtitle_profiles():
    isversion = xbmcaddon.Addon('inputstream.adaptive').getAddonInfo('version')
    subtitle_profile = ['webvtt-lssdh-ios8']
    if g.ADDON.getSettingBool('disable_webvtt_subtitle') \
        or common.is_minimum_version(isversion, '2.3.8'):
        subtitle_profile = ['simplesdh']
    return subtitle_profile`

to

`def _subtitle_profiles():
    isversion = xbmcaddon.Addon('inputstream.adaptive').getAddonInfo('version')
    return ['webvtt-lssdh-ios8'
            if common.is_minimum_version(isversion, '2.3.8') and not g.ADDON.getSettingBool('disable_webvtt_subtitle')
            else 'simplesdh']`

makes everything works fine.

**Comment by Essam315** [comment]
@CastagnaIT 
The last modification makes WebVTT subtitles disabled by default, changing from

`def _subtitle_profiles():
    isversion = xbmcaddon.Addon('inputstream.adaptive').getAddonInfo('version')
    subtitle_profile = ['webvtt-lssdh-ios8']
    if g.ADDON.getSettingBool('disable_webvtt_subtitle') \
        or common.is_minimum_version(isversion, '2.3.8'):
        subtitle_profile = ['simplesdh']
    return subtitle_profile`

to

`def _subtitle_profiles():
    isversion = xbmcaddon.Addon('inputstream.adaptive').getAddonInfo('version')
    return ['webvtt-lssdh-ios8'
            if common.is_minimum_version(isversion, '2.3.8') and not g.ADDON.getSettingBool('disable_webvtt_subtitle')
            else 'simplesdh']`

makes everything works fine.

**Comment by CastagnaIT** [comment]
Oh, my oversimplification. Last night, i was melted down from work.. Forgotten an "not" thankyou!!
for the VP9 would be to understand also the reason of caphm decision to have it set active by default unfortunately it's not all well documented

**Comment by Essam315** [comment]
He made VP9 on by default because at this time Netflix made many changes resulted in no playback was  working unless VP9 was enabled, now we do not need this, and here in 0.13.XX you will notice that the developer made VP9 optional again after it became needless.

https://github.com/asciidisco/plugin.video.netflix/commit/fe53bce6063252b021c0716ff635b0d1153c6781

This was the first solution

https://github.com/asciidisco/plugin.video.netflix/pull/519#issuecomment-439276151

then that one

https://github.com/asciidisco/plugin.video.netflix/pull/519#issuecomment-439338258

more information

https://github.com/asciidisco/plugin.video.netflix/pull/519#issuecomment-440480430


here VP9 was optional

https://github.com/asciidisco/plugin.video.netflix/pull/519#issuecomment-440794887

here is the reason for using VP9

https://github.com/asciidisco/plugin.video.netflix/pull/519#issuecomment-441029901

**Comment by Essam315** [comment]
Sorry, but WebVTT still need to be fixed, you need to add "and not" before "g.ADDON.getSettingBool('disable_webvtt_subtitle')", in which WebVTT works if 'disable_webvtt_subtitle' was off, please use this code, i tested it and 100% working.

def _subtitle_profiles():
    isversion = xbmcaddon.Addon('inputstream.adaptive').getAddonInfo('version')
    return ['webvtt-lssdh-ios8'
            if common.is_minimum_version(isversion, '2.3.8') and not g.ADDON.getSettingBool('disable_webvtt_subtitle')
            else 'simplesdh']

**Comment by CastagnaIT** [comment]
the setting disable_webvtt_subtitle works in reverse mode, no needed the "not" term, you have wrong settings in your addon

**Comment by Essam315** [comment]
Sorry, everything working fine now.
