### ISSUE TITLE
Multi profile sync 'My List' unsupported?

### ISSUE THREAD

**Issue by stefanheijnen** [CastagnaIT/plugin.video.netflix#412]
#### Your Environment
- Netflix add-on version: v0.16.1
- Operating system version/name: CoreELEC 9.2.1
- Device model:  Odroid C2

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe your help request
Our family has multiple profile's on 1 Netflix account. I use the function to keep My List and my library synchronized. We regularly switch profiles and I noticed sync isn't working correctly. Sometimes it sync a few shows from 1 profile, and a few from another. But never all shows from all profiles. For now I autologin to one profile and sync this. Works perfect. But this significantly decreases the WAF.

It it possible to sync multiple profiles or should it be a feature request?

**Comment by CastagnaIT** [comment]
Just a profile can be synchronized with the Kodi library,
the system is already complicated and it is already risky to use it this way:
[Notice for the use of auto-update and auto-sync with Netflix "My List" feature](https://github.com/CastagnaIT/plugin.video.netflix#notice-for-the-use-of-auto-update-and-auto-sync-with-netflix-my-list-feature)
multiple profile synchronization functionality will never be implemented.

> We regularly switch profiles and I noticed sync isn't working correctly
> Sometimes it sync a few shows from 1 profile, and a few from another.

this is weird,
and to understand i need exaclty what you do step-by-step to reproduce the issue

**Comment by kidforpm** [comment]
> > We regularly switch profiles and I noticed sync isn't working correctly
> > Sometimes it sync a few shows from 1 profile, and a few from another.
> 
> this is weird,
> and to understand i need exaclty what you do step-by-step to reproduce the issue

I think what he is saying is that they use multiple user accounts within the netflix account. Since they will all select a different account in the plugin to watch their shows, a different "profile" will be active at the time of the auto sync, and thus scrap the sync and repopulate the library.

That is exactly how the plugin is intended to work, but it will not fit with the usercase of different users using the same Kodi profile wanting to see different content. 

I think the autosync functionality is not very useful for multiple netflix accounts in one profile. You can use Kodi to set up different profiles ("users") and I believe they can have both different content libraries and maybe also use different settings for their plugins. Do note that if you can set different settings for the plugin for different users, also to double check the location where the netflix plugin drops media, and alter it for different accounts so it doesn't overwrite other users.
Maybe you can give that a try, I have never used it and am not sure how it works. Check the kodi forums for details on multiple and their plugin settings in Kodi (see settings -> Profiles).

**Comment by CastagnaIT** [comment]
so now understand, it is not possible to use more than one netflix accounts with auto synchronization enabled, this would cause problems of various kinds...

the only solution is to add multiple Kodi profiles, for each netflix account
so that you can separate the addon settings by Kodi profile

After activating multiple Kodi profiles you must also check the exact path of the folder where the tvshows/movies are exported

i have never tested multiple Kodi profiles,
maybe you can let us know

**Comment by stefanheijnen** [comment]
> I think what he is saying is that they use multiple user accounts within the netflix account.

Yes this is what we do. Likes this:

![image](https://user-images.githubusercontent.com/1306331/71720916-8c40a000-2e23-11ea-93ca-9fd34adb6721.png)


> the only solution is to add multiple Kodi profiles, for each netflix account
> so that you can separate the addon settings by Kodi profile

I'll check with the wive if that's acceptable. If so, then I'll test Kodi's multiple profiles function and let you know what my findings are.

**Comment by kidforpm** [comment]
> > I think what he is saying is that they use multiple user accounts within the netflix account.
> 
> Yes this is what we do. Likes this:
> 
> ![image](https://user-images.githubusercontent.com/1306331/71720916-8c40a000-2e23-11ea-93ca-9fd34adb6721.png)
> 
> > the only solution is to add multiple Kodi profiles, for each netflix account
> > so that you can separate the addon settings by Kodi profile
> 
> I'll check with the wive if that's acceptable. If so, then I'll test Kodi's multiple profiles function and let you know what my findings are.

check where the plugin outputs its HTTP shortcuts. They might overwrite eachother. You can manually change it in the plugin settings

**Comment by stefanheijnen** [comment]
Ok, I've setup up 2 different profiles. Both profile log in to the corresponding Netflix profile and sync their My List with their own Kodi library.

There is only 1 small issue: After changing profiles in Kodi the Netflix plugin keeps logged in to the previous profile. A simple Kodi restart fixes that. But I hope you can give that a more elegant fix :wink:

**Comment by CastagnaIT** [comment]
to avoid restarting, you can also try to open context menu on addon icon and perform disable/enable addon
I will investigate to this problem

**Comment by CastagnaIT** [comment]
@stefanheijnen Can you do a test?
Here: [plugin.video.netflix_0.16.1_20200105_t1.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4023363/plugin.video.netflix_0.16.1_20200105_t1.zip)

so then i can start preparing the release for the new version

**Comment by stefanheijnen** [comment]
That works perfect! I switched a few times between the 2 profiles and every time the correct my list was displayed.

Thank you for the quick resolution.
