### ISSUE TITLE
Playback problems on Raspberry Pi (LibreELEC)

### ISSUE THREAD

**Issue by acixx** [CastagnaIT/plugin.video.netflix#471]
I'm running LibreElec 9.2 (Kodi 18.5) on a Raspberry Pi 3B+ and can't watch Netflix since about a month. 

Playing a video, there is either
- both video and audio missing (ie 28 Days Later on German account))
or
- video looks like encrypted-analogue-tv in the 90s, sound first okay later stuttering (ie 28 Weeks Later on German account)

I'm experiencing the problem with version: 0.16.4, also tried the current master branch. Problem first occured when I was still using 0.16.1.  I have since then reinstalled the add-on and reverted all settings to default. Also tried limiting to 720p (my netflix-account doesn't allow more). 

The debug log is [here](https://github.com/CastagnaIT/plugin.video.netflix/files/4142879/kodi.log).

**Comment by dagwieers** [comment]
I think you have OMXPlayer enabled in **Settings » Player**.
If you disable OMXPlayer, Netflix will work again as expected.

**Comment by acixx** [comment]
This is correct @dagwieers, I have no idea why this has been enabled but disabling it makes Netflix work again.

Thank you very much, case closed!

**Comment by CastagnaIT** [comment]
@dagwieers can you provide me some more info about OMXPlayer setting? (i dont have RPI)
is it enabled by default?
is it necessary to have a more performing reproduction with video local files or is needed for what other purpose?
i can not found the settings file, do you know the code-name of this setting? (otherwise i ask the le devs no problem)

**Comment by dagwieers** [comment]
@CastagnaIT Sure, the option to disable/enable OMXPlayer is in the settings at: **videoplayer.useomxplayer** and it is disabled by default.

Why would people enable it? Well, due to playback issues on some streams with the default player on Raspberry Pi, some users have to enable the OMX Player in Kodi. (In our case the Vier/Vijf/Zes streams from Retrospect require the OMX Player) But obviously if they also use Netflix, like we do, you have to enable/disable it yourself. It would be nice if Netflix would check and ask to fix before playing. (Or maybe if that is at all possible, select the right player when playing, but leave the setting alone).

You can find some information here:
https://github.com/retrospect-addon/plugin.video.retrospect/issues/1089
