### ISSUE TITLE
jsonrpc method to open a video

### ISSUE THREAD

**Issue by Nanoseb** [CastagnaIT/plugin.video.netflix#501]
## Feature request
I'm submitting a proposal to ...
  - [x] new feature
  - [ ] change an existing feature

### Describe your request
With the youtube plugin it is possible to browse youtube on a remote device (phone, web browser etc.) and to send to kodi a request to watch the current video with it. This is done with extensions like [send-to-kodi](https://addons.mozilla.org/en-US/firefox/addon/send-to-xbmc-kodi/) or the Kore app on android (thanks to a jsonrpc method). Would it be possible to have the same with netflix and this plugin?

#### Describe the use case
I have kodi set up on a TV, however it is way easier to browse netflix on my phone or a laptop. Hence this will bring the two together and have an experience a bit similar to what a chromecast provides.

#### Development tips
This is the kind of request used for youtube (from [here](https://github.com/allejok96/send-to-kodi/blob/master/send-to-kodi.sh)):
```  
curl \
	${user:+--user "$user:$pass"} \
	-X POST \
	-H "Content-Type: application/json" \
	-d '{"jsonrpc":"2.0","method":"Player.Open","params":{"item":{"file":"plugin://plugin.video.youtube/?action=play_video&videoid=dQw4w9WgXcQ"}},"id":1}' \
	http://$host:$port/jsonrpc
``` 

PS: Sorry if this feature already exist, and if so, what would be an example of POST request to send to kodi to have this?

**Comment by CastagnaIT** [comment]
I think there is the possibility to try adding support for an browser extension in order to play via remote, but the extension mentioned is compatible only with firefox

would be an interesting function, but i don't find it correct to force all users to install a browser that they may not want, just to make an extension work, the extension must be developed to support at least two of most used browsers

also it is necessary that the developer of the extension actively cooperates here to be able to do the integration

---

For android,
i do not understand how you're planning to integrate this
the official app does not provide an episode/movie sharing feature

where do you think to get the shared-links of episode/movie?
Can Kore convey links to a specific addon? If so, how?

**Comment by Nanoseb** [comment]
I agree with you, you shouldn't be forced to use firefox. Here I just linked an example of extension but there are several more for firefox and chrome (like [this](https://chrome.google.com/webstore/detail/send-to-kodi/fobjnlgachlcppfalhpnmdllmjnfmfah)). 
I think the best approach would be implement this in the netflix plugin, document it and then let the extension dev know the support of netflix. Since they already support youtube etc. adding netflix support is quite straight forward for them (I will be happy to make some PR for that).

About the android support. I do have a share button on movies and tv series pages on my app (though I just realised that there is no way to share a specific episode in a series but only the "series" itself).
How it works for youtube is that you play a yt video normally, hit the "share" button and press "Play on Kodi" (that the Kore app advertise). Kore itself realises it is a youtube link and then sends a jsonrpc request similar to the one I put in my original post (implemented [here](https://github.com/xbmc/Kore/blob/master/app/src/main/java/org/xbmc/kore/ui/sections/remote/RemoteActivity.java#L527)). So there is some dev needed on Kore side, but again it looks quite straight forward to add netflix support since they already support youtube, vimeo, soundcloud etc.

**Comment by CastagnaIT** [comment]
> I agree with you, you shouldn't be forced to use firefox. Here I just linked an example of extension but there are several more for firefox and chrome (like this)

before spending time on this development, i will need to know if the two developers of these extensions agree with this, you can try ping them here.
If both devs consent, i will develop the code and provide them the entry point url

---

On android to have only the code of the tvshow instead the episode is limiting,
and unfortunately this addon has not been officially accepted into Kodi repository due to possible legal issues from Netflix Inc. to Kodi Foundation,
so it is excluded to modify the Kore source code, to implement specific features related to this add-on

**Comment by Nanoseb** [comment]
Sure I understand, will ping them and see their respond.

For Android, ok that's a shame but I understand. If I ever go into android dev, I might try to make a minimal app that does just this, it looks like a good first project.

Anyway, thanks for your time and for considering it, I'll create issues on some browser app pages and see what they reply.

**Comment by CastagnaIT** [comment]
> For Android, ok that's a shame but I understand. If I ever go into android dev, I might try to make a minimal app that does just this, it looks like a good first project.

in reality there may be an alternative and more elegant way for Kore,
but it takes a bit of work and needed someone who wants to spend a bit of his time

To now the management to send instruction in a remote way seem to me hardcoded,
then you could add a system to load an external configuration file, so as to make a closed system dynamic.

In this configuration file (xml, json, etc) you could insert to example two field, the type of url-link to accept, and where to give the remote commands on Kodi, in this way each addon can put in its configuration.
Then no legal problems, and more users/devs happy because can be implemented in any kind of addon

This is an example do not take it literally (in any case you must consult the Kore/Kodi developers)

**Comment by sobralik** [comment]
Yatse is another remote control app for Kodi and this issue was [brought up in their forums](https://community.yatse.tv/t/netflix-addon-cannot-be-controlled-via-yatse/402)  a while back. Maybe that can provide some information on what needs to be done to get this working.

**Comment by CastagnaIT** [comment]
if there is no news, i will close for inactivity

**Comment by Nanoseb** [comment]
Hi,
Sorry for not giving update, I don't have access to kodi anymore these days and I didn't want to push for this until I do (to test things etc.). So feel free to close this, and we could reopen it again in the future.

**Comment by CastagnaIT** [comment]
all right, thanks for given a response
