### ISSUE TITLE
X

### ISSUE THREAD

**Issue by warcry2000** [CastagnaIT/plugin.video.netflix#504]
X

**Comment by notoco** [comment]
Who is "they"? Any proofs?

**Comment by warcry2000** [comment]
It was connecting to the plugin with username and password, being a few seconds and indicating that I was no longer connected. And I could no longer connect from any device with my user, indicating that it was not the password.

**Comment by CastagnaIT** [comment]
making judgments without describing the real problem is to the detriment of the addon and especially your face

**Comment by CastagnaIT** [comment]
correct the information and also the title otherwise i will immediately close this stupid post

**Comment by CastagnaIT** [comment]
Just to let people know who are perplexed:

- The Login is done in the same way as on the website, through the secure HTTPS protocol
- The credentials, in all the future requests sent to the Netflix server are sent only in encrypted MSL form, a protocol designed by netflix, to achieve a high degree of protection
- The credentials in the local computer are stored in a in encrypted form, mostly related to the device in use, so that any copy made by intruders of the database, makes it _impossible_ to use and/or decrypt the credentials contained in the database on other devices
- As open source code, it is clearly visible that there are no malware parts

In any way, Netflix has always had the last word,
and may reserve the right to change the password at any time, in according to their protection algorithms:
Official document: https://help.netflix.com/en/node/56461

if that's not enough, and there is a way to data breach:
- first rule, do not expose the data breach system to the whole world, as this post would like to do, then send in a private way
- second, send the information step by step, with as much information as possible to reproduce the problem as described in the guide
