### ISSUE TITLE
Netflix Addon vr.1.0.0

### ISSUE THREAD

**Issue by yabba235** [CastagnaIT/plugin.video.netflix#506]
#### Your Environment
- Netflix add-on version: 1.0.0
- Operating system version/name: LibreELEC.tv Matrix build #0301
- Device model:  Zotac MI553

Used Operating system:
* [ ] Android
* [ ] iOS
* [ x] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

With [python] set abi to 3.0.0 in Libreelec build 0301 Netflix add-on stops work.
Perhaps add-on is not compatible with python ABI 3.0.0

**Comment by Essam311** [comment]
As a temp solution you could modify `addon.xml` from 

`<import addon="xbmc.python" version="2.26.0"/>`

to

`<import addon="xbmc.python" version="3.0.0"/>`

and do the same thing for "script.module.addon.signals-0.0.5" and "script.module.inputstreamhelper-0.4.4" and install the files manually. You could use the files from here, I modified them for my personal use.

[plugin.video.netflix-1.0.0.py3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4304804/plugin.video.netflix-1.0.0.py3.zip)

[script.module.addon.signals-0.0.5.py3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4304807/script.module.addon.signals-0.0.5.py3.zip)

[script.module.inputstreamhelper-0.4.4.py3.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4304810/script.module.inputstreamhelper-0.4.4.py3.zip)

**Comment by yabba235** [comment]
Thank’s for tips - I try it  when go home.

W dniu pon., 9.03.2020 o 06:42 Essam311 <notifications@github.com>
napisał(a):

**Comment by CastagnaIT** [comment]
I'm in the red zone of coronavirus (venice province) and at least to now i am secure

there have been some cases some days ago my hospital but they have been isolated and quarantined, unfortunately some nurses have been infected..

yesterday they started setting up roadblocks on the streets
no one can go outside or enter the country or provinces, otherwise you will be sanctioned or in the worst cases imprisoned

many public places remain closed school, shops, pubs and bar, churches, fairs, events (in this period we are full of events for the carnivals, all canceled) at weekends even shopping centers are forced to close
some shops can stay open anyway, but they have to close in the late afternoon

a lot of people got scared, and started running away from north Italy to south italy
police had to block the trains and buses and send them back here (to north Italy)...
foreign people are very scared, because uneducated Italians behave badly with them, therefore most of them Chinese bars, shops and restaurants have been closed for weeks already...

today the citys is quite empty, who can still go to work, only if they work near home, many families and children are at home, here we are in quarantine until next month.. i hope it ends soon
