### ISSUE TITLE
STRM Resume workaround not works

### ISSUE THREAD

**Issue by elbowz** [CastagnaIT/plugin.video.netflix#523]
## Bug report
The resume movie works only on a single file at once, and stop working also on this one after Kodi restart.

This is a regression, see #199 

#### Your Environment
- Netflix add-on version: 1.0.0
- OS: Arch Linux
- Device model:  

Used Operating system:
* [ ] Android
* [ ] iOS
* [X] Linux
* [ ] OSX
* [ ] Raspberry-Pi
* [ ] Windows

### Describe the bug
https://pastebin.com/77EpYN2y

#### Expected behavior

The movie resume from the latest interrupted point.

#### Actual behavior

Play the move from start
#### Steps to reproduce the behavior

1.
2.
3.

### Debug log

The debug log can be found from this link:
https://pastebin.com/77EpYN2y

#### Installation
* [x] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by CastagnaIT** [comment]
Missing debug info in the log, instruction on the Readme

what is the latest version of the addon that resume works?

**Comment by elbowz** [comment]
I don't know...you can refer to #199 to find one where it worked.

On your device does it works?

**Comment by CastagnaIT** [comment]
I don't have every kind of operating system or type of devices available for every user who has problems...

the fix introduced with the version specified in 199, hasn't been touched
"recently" the "resume" workaround has been modified due to problems with Libreelec and it was working
so the problem is elsewhere but your log is not helpful

**Comment by CastagnaIT** [comment]
I do not know what's changed in Kodi core
but the problem seems more serious because it is no longer recognized when a video is played from outside the addon (e.g. library)

Unfortunately Kodi does not provide a reliable method to determine this..

**Comment by elbowz** [comment]
> I do not know what's changed in Kodi core
> but the problem seems more serious because it is no longer recognized when a video is played from outside the addon (e.g. library)
> 
> Unfortunately Kodi does not provide a reliable method to determine this..

So affect all device?

If you cannot reproduce the bug i'll provide the debug log ASAP

**Comment by CastagnaIT** [comment]
I don't know if it affects all systems,
but if something has changed in the Kodi core it is possible

I did two tests on Windows and not worked,
i need to know if on LibreElec works or not, but in this moment i don't have an updated LibreElec system in order to do a test

**Comment by elbowz** [comment]
I can say you that also on Linux not works...

**Comment by CastagnaIT** [comment]
after rebooting Kodi has started again recognized when a video is played from outside the addon...Kodi sometimes behaves strangely...

but seem there is a problem with getting the data from the library again
I'll have to look into

**Comment by elbowz** [comment]
Thanks!

**Comment by elbowz** [comment]
Sorry, unrelated new feature request.

A plug-in context-menu to force sync Netflix mylist with Kodi library.

So we can disable the scheduled one and we don't have to enter in plugin setting to start the synching process.

Do you think could be useful and maybe easy to implement?

Thanks as usually

**Comment by CastagnaIT** [comment]
Please install:
[plugin.video.netflix_1.0.0_20200316.zip](https://github.com/CastagnaIT/plugin.video.netflix/files/4340120/plugin.video.netflix_1.0.0_20200316.zip)
and let me know

---

>  plug-in context-menu to force sync, Netflix mylist with Kodi library

almost all is possible,
but this could encourage users to use the menu also many times in a short space of time

you have to keep in mind that not all users have a "my list" with few elements, but also hundreds and more

this could lead to an increase of cases where the user's account could be blocked from netflix due to excessive requests to the server

I'm not sure that this is a good idea

**Comment by elbowz** [comment]
Your zip works perfectly!!

The video resume now works like a charm :)

...and thanks for your fully explaination about the requested feature. I didn't know the Netflix limitation API, so it seems reasonable don't implement that feature.

Thanks again!

**Comment by CastagnaIT** [comment]
Good to ear
