### ISSUE TITLE
Locked account while exporting library

### ISSUE THREAD

**Issue by DAVIZINH0** [CastagnaIT/plugin.video.netflix#55]
*I'm submitting a ...*
  - [* ] bug report

### Addon version used

plugin.video.netflix_0.14.0beta23

### Description

When i trying to sync all my list, exporting it to a folder.
It allways stop in the proccess and never finish.

If I sync the series one to one "adding it to library". after 10 or 15 series. the netflix account is blocked.
I must chat wit netflix to unlock and wait 24hours.
Which is the metod to export the library? maybe is much agresive and lock the account?
i dont know :-(

This is a great feature, and i love it!!!. But the locking problem is a big problem :-(

### Operating System
* [*] Windows (x86/x64)
* [*] Android

**Comment by CastagnaIT** [comment]
export to the library, is a careless system, if it were for me I would delete this option, because it does not work well for various reasons.
Those who use it use it at their own risk.
it would be better to put a warning but I would not know exactly where.

The more content you enter, then more requests you make to the server, you have too many tv series, consequence account blocked

solution is to have a few tv series, or use "My list" menu provided for this purpose by netflix

**Comment by DAVIZINH0** [comment]
hello again.
thanks for the info!
the problem is only in the first sync or every day if you activated the sync new chapters every day? 

I have all the strm files for 90% of my list and Its great!.  maybe the solution is have only the active series in my list....

**Comment by dm2912** [comment]
just to update on this.

last night i added REsurrection: ERtugrul to my library

thats 390 episodes....

it added them all in a matter of seconds and no lockout :D

**Comment by Smeulf** [comment]
@dm2912 it's not a matter of the number of season or episodes, bit the number of series you add in a small amount of time.

A series with 1 season 10 episodes or 25 seasons/ 2500 episodes is the same regarding the number of requests to the servers: 1.

Unless you add the seasons one by one of course, then it's one request per season ^^
