### ISSUE TITLE
Use of MySQL setting and unable to connect to MySQL server error

### ISSUE THREAD

**Issue by nonobio** [CastagnaIT/plugin.video.netflix#562]
#### Your Environment
- Netflix add-on version: 1.1.1
- Operating system version/name: Windows 7 on main Kodi, LibreElec on others Kodis
- Device model:  Desktops PC and NAS Synology DS107+

Used Operating system:
* [x] Linux
* [x] Windows

### Describe your help request
Hello,

First, thanks a lot for this add-on :)

I use it on Kodi 18.6 on several devices, from Win 7 PC to LibreElec. My Kodi's video library is shared with Mysql database running on a NAS.

In the add-on's settings i have customized the export to library folder with a smb path : all is working fine : i can export on one PC from add-on to library, and i retrieve my show or movies on my others devices.

But i'm suprised to find a Mysql setting in the add-on : i wasn't using it (disabled) but as i'm using MySQL database sharing, maybe i should use it ?

So i tried to enable it, i changed the IP with the one of my NAS, checked my user and password, and the port.

When i apply with "OK", the add-on show a notification "Unable to reach the MySQL server" then the setting is disabled.

**So i have 2 questions :**

1- What the aim to use this MySQL setting ? I don't understand why it is necessary : if i export a movie or show on one device, then i analyze my Kodi video library to find the exported media : it is automaticly synced with my existing MySQL video database...
2- If i should use it, do you know why the add-on can't reach my server ? (my Kodi on the same device can...)

As i said, without this setting all is working fine, but i'm just curious ;)

Thanks

#### Screenshots
![Netflix add-on MySQL setting](https://user-images.githubusercontent.com/7425799/78991503-5ce3b280-7b39-11ea-9ced-ecfd687c0899.jpg)

![Netflix notification error MySQL connection](https://user-images.githubusercontent.com/7425799/78991623-a2a07b00-7b39-11ea-8d77-fc4320a514a3.jpg)

My advanced settings file used since a long time to share my Kodi database :

 `<advancedsettings>
<fullscreen>true</fullscreen>
<videodatabase>
<type>mysql</type>
<host>192.168.1.6</host>
<port>3306</port>
<user>kodi</user>
<pass>****</pass>
</videodatabase>
<pathsubstitution>
 <substitute>
    <from>special://profile/favourites.xml</from>
    <to>smb://192.168.1.6/kodi/favourites.xml</to>
  </substitute>
</pathsubstitution>
</advancedsettings>`

[Post on kodi forum.](https://forum.kodi.tv/showthread.php?tid=329767&pid=2938995#pid2938995)

**Comment by CastagnaIT** [comment]
Yes i think is missing a Wiki documentation for MySQL option, so then:

### 1) it all depends on the type of use you have to do:

First of all take into account that Netflix add-on has an internal database of exported items and use it to manage Kodi library. So if the Kodi library will be modified externally it will cause inconsistencies with the internal Netflix database.

**Use case 1 - [MySQL not needed]**
**Manage the exported items from ONLY a single device, and use the library as _read only_ from the other devices**

In this case, from the main device where you manage the library, you can set how you prefer the synchronization of the library (add-on settings->Library->Auto update mode)

_But only from the Kodi of this main device you can modify the exported items._
If you will try to modify the exported items of Kodi library from Kodi of other devices, you will create problems with the internal Netflix database (of the main device). That in the worst cases will create extra work for synchronization by increasing the risk of ban cases of Netflix account.

**Use case 2 - [MySQL needed]**
**Manage exported items from all devices**

In this case, will be needed to share also the internal Netflix database with all devices (in the same way as Kodi database).
To activate the feature is explained here: [Use MySQL shared library database](https://github.com/CastagnaIT/plugin.video.netflix/wiki/Library-settings#use-mysql-shared-library-database)

In this way you can modify the exported items of Kodi library from Netflix add-on of any device,
because every library change will be reflected (by MySQL) on every device that has Netflix add-on installed.
This avoids the risk of inconsistencies in the internal Netflix database or wrong synchronizations.


### 2) Needed more info
if Kodi MySql works with all devices successfully,
I can't know what could be wrong without debug log,
For Kodi debug log instructions in the Readme

**Comment by nonobio** [comment]
Hello CastagnaIT :)

1- Thanks a lot for the wiki updated. I read it and all is clear now. So i was using the add-on with the option 2, but in a wrong way because i was managing my kodi library of exported items whatever the device !
I will now use the Option
But before, should i do any clean task of my old settings/use on one or all devices ?

2- I quicky look at my kodi debug log and found this:
`[plugin.video.netflix (0)] MySql error 1115 (42000): Unknown character set: 'utf8mb4'`

I also found other general mysql notice and warning:
`2020-04-13 09:19:59.067 T:21104  NOTICE: MYSQL: Connected to version 5.1.49-log
2020-04-13 09:19:59.067 T:21104 WARNING: MYSQL: Your database server version 5.1.49-log is very old and might not be supported in future Kodi versions. Please consider upgrading to MySQL 5.7 or MariaDB 10.2.`

Tell me is it is sufficiant for diagnose my issue and/or if you want my complete debug log ?

Thanks again :)
Bruno

**Comment by CastagnaIT** [comment]
Hi
1) I think it is better reinstall add-on on each device (by deleting user data when requested)
2) Your version of MySQL is outdated, there is needed:
MySQL minimum 5.5.3
or
MariaDB minimum 5.5

so if you can update it, otherwise you can't use it

**Comment by nonobio** [comment]
Hi,

Ok, i'm doing all this work.

I will install a newer database on another NAS more recent. I don't know MariaDB.

What's your recommandation ? I only use MySQL database for Kodi. Should i install MariaDB or MySQL ?

Thanks

**Comment by nonobio** [comment]
Hi

1.Done !
2. Done :)
My actual database was installed on a old NAS with old MySQL version.
I installed MariaDB 10.3.7-0051 on my more recent second NAS and installed my Kodi Library on it. Then i reinstalled Netflix Add-on and the connexion to the MySQL base is ok now !

Thanks a lot !
Have a nice day :)
Bruno

**Comment by CastagnaIT** [comment]
very well!
