### ISSUE TITLE
Can't play any video, error: "TypeError: function missing required argument 'line1' (pos 2)"

### ISSUE THREAD

**Issue by Allesstein** [CastagnaIT/plugin.video.netflix#607]
#### Your Environment
- Netflix add-on version: 1.20
- Operating system version/name: LibreElec 19
- Device model:  Raspberry Pi 3+

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [ v] Raspberry-Pi
* [ ] Windows

### Describe the bug

After trying to play any movie or show in the add-on the error appears

#### Expected behavior

play the selected movie

#### Actual behavior

error appears, movie doesn't play

#### Steps to reproduce the behavior

1. select any movie
2. hit play

### Debug log

The debug log can be found from this link:
https://drive.google.com/open?id=1AXjk4v9FPc8Fg2u6Ttg4i31peB1gjFuH

#### Installation
* [ ] I'm using other Netflix Repo 
* [ ] I'm using a different source

**Comment by Essam311** [comment]
This problem is with inputstreamhelper, your build of Kodi 19 is old, you need to use the newest build or try using an older version of inputstreamhelper, try installing this one manually.

https://github.com/emilsvennesson/script.module.inputstreamhelper/releases/download/v0.4.4/script.module.inputstreamhelper-0.4.4+matrix.1.zip

**Comment by Allesstein** [comment]
i updated my Kodi build and it works now. Thank you!
