### ISSUE TITLE
Stream resolution settings not persistent

### ISSUE THREAD

**Issue by fesarlis** [CastagnaIT/plugin.video.netflix#614]
Hello.
My kodi display is shown at 1080p.
I would like to enforce the following behaviour:
1. 1080p and larger videos to play at exactly 720p.
2. Smaller videos (eg 540SD) to play at the maximum possible resolution and bitrate (eg 960x540, not 768x432). 

Tried to configure this via Inputstream Adaptive settings and also using the "Limit video stream resolution". It does not seem to work, and if I choose the stream manually even if I use "Set as default" the changes are not persistent.

Any help would be appreciated.

**Comment by jakermx** [comment]
If you set the Limit video stream resolution ,what the plugin will do, is get the max available stream....this feature override inutstream settings, since it grabs the manifest data and  passes the max available, deending on the codecs you enabled,  to the player who  calls input stream....

I would suggest to set the input stream plugin by defaulr and set the limit to 720p

cheers

**Comment by CastagnaIT** [comment]
do not touch Inputstream Adaptive settings,
go to add-on `Expert` settings and on `Limit video stream resolution to` set 720P

in your case lower resolution are selected only when 720P do not exists
