### ISSUE TITLE
Feature request : Sort My List (or any other list) by label

### ISSUE THREAD

**Issue by Smeulf** [CastagnaIT/plugin.video.netflix#72]
*I'm submitting a ...*
  - [ ] bug report
  - [X] feature request
  - [ ] support request

## General information

With a large list, it's getting sometime hard to find what you want to see.  So I wish I could sort My List by label, and sort it again 'by default' if I need it.

For now, I was able to implement the label sorting by adding xbmcplugin.addSortMethod(g.PLUGIN_HANDLE, xbmcplugin.SORT_METHOD_LABEL) in the Kodi/Listings.py file in the 'sort_nothing' case.

But even if I replace SORT_METHOD_NONE by SORT_METHOD_UNSORTED, I can't sort it again 'by default' until I exit the view and get in again. This is the expected behavior for sorting (https://forum.kodi.tv/showthread.php?tid=174921), but if you have an idea to make it work, that would be awesome.

Thanks!

Smeulf.

**Comment by CastagnaIT** [comment]
I don't understand why you need to order the page result,
is just 100 results per page,
I'll never put sorting on the lists
for these reasons:
-the paged lists are a workaround because kodi does not support them
-the sort method mix the next/previous "buttons"
-ordering the results paged with the kodi sort method, involves a mixture per page, which does not respect the queries returned by the service

so the sort order can be applied only via query through the appropriate option in the settings->views

**Comment by Smeulf** [comment]
Well, even 100 results per page, it's sometime confusing for me if it's not sorted.

About the next/previous page, if I remember correctly, there's a way to put then at the beginning or the end of a list.  The 'Extra' addon uses it as far as I remember.

But it's ok for me if you don't want to implement it ;)

Just now, I'm trying to determine what view I should use to have My List ordered by title. Can you give me some tips ?

Thanks.
