### ISSUE TITLE
Crash at start on DietPi

### ISSUE THREAD

**Issue by hiroweeb** [CastagnaIT/plugin.video.netflix#746]
#### Your Environment
- Netflix add-on version:  1.6.1
- Kodi version: 18.2
- Operating system version/name:  DietPi 6.31.2
- Device model:   RPi 2B

Used Operating system:
* [ ] Android
* [ ] iOS
* [ ] Linux
* [ ] OSX
* [X] Raspberry-Pi
* [ ] Windows

### Describe the bug

Since early versions of the Netflix addon I've used (1.3.1 I believe), I've never been able to make it work. If I configure it beforehand, I just cannot get a login button, it seems to be logged it in someway and only offer for a "Logout" button. Clicking on the button results to the same issue as if I wanted to open it : a generic error toast, no help whatsoever about what is going on.
I installed the latest version and got the same issue.
Tried looking through the log but can't help unfortunately.

#### Expected behavior

- Enter login info
- Open addon
- Watch movies

#### Actual behavior

- Can't enter login info (only logout button)
- Open addon
- Crash

#### Steps to reproduce the behavior

1. Get DietPi 
2. Install addon and dependencies
3. Open addon

#### Possible fix

No clue at all.

### Debug log

The debug log can be found from this link:
https://0x0.st/its9.log

#### Installation
* [X] I'm using CastagnaIT's Netflix Repo 
* [ ] I'm using a different source 

#### Other information

Haven't checked at all if log was set to verbose, tell me if it isn't and I'll reupload a log with proper settings.

**Comment by CastagnaIT** [comment]
i do not know DietPi system and the Pyhon errors are weird
i think something is missing, perhaps some RPI user can help you

**Comment by wagnerch** [comment]
Lots of errors about opening files, or files too small, or truncated, suggest maybe your filesystem is full, read only, or something else.  The other thing is you shouldn't run Kodi as root.

My guess is your filesystem is full and a whole bunch of the python files delivered with the addon are truncated, which is why they fail to import.


I run Kodi w/ Netflix addon on Raspbian Lite Buster (no X, no Wayland) on a Pi 4, and OSMC Vero 4K+, and have ran it on Windows until recently.  It runs totally fine.  There are some additional tasks to do like install python-pycryptodome.
