### ISSUE TITLE
Legal issue

### ISSUE THREAD

**Issue by akamom** [CastagnaIT/plugin.video.netflix#751]
While installing the Netflix Add-On, it tells me, that some parts of this add-on may not be legal in my country.

What parts can be illegal for my country? It is hard to figure it out if you don't know what can be illegal.

**Comment by CastagnaIT** [comment]
is a phrase that was written many years ago by the developer who started the project
i do not know the original reason why the original author chose this specific words.
Basically this project replicates some parts of functioning of the website.

I think the phrase could be improved in this way:

_Using this add-on may not be legal in your country of residence - please check with your local laws before installing._

Because in some countries Netflix is banned and so not allowed

**Comment by akamom** [comment]
Thank you for this fast response. Never thought to get an answer to this rather small and silly-sounding question.
