### ISSUE TITLE
[Feature Request] Associate selected profile with Favourites item

### ISSUE THREAD

**Issue by ashleysommer** [CastagnaIT/plugin.video.netflix#760]
## Feature request
I'm submitting a proposal to ... 

  - [x] new feature

### Describe your request
Is it possible to save a selected profile to a 'favorites' shortcut?

#### Describe the use case
Related to: https://github.com/CastagnaIT/plugin.video.netflix/issues/718

If I save a video to my Kodi 'Favorites' (using Add to Favorites from the context menu), then when I play the video from my favorites menu, it will always ask me to select my Profile.

If I save a series to my Favorites, when I open the series it opens the item without asking to choose my profile, but if I select a video in the series and choose "Play From Here", then it asks for my profile before playing _every video in the series_.

In the settings I have set which profile to export by default, but my understanding is that is only when saving a video or series to My Library, not to favorites.

**Feature:** I'd like to add an item to favorites, and have it save the associated Netflix profile, so when I play the item from the favorites menu, it doesn't ask to choose my profile every time.

#### Describe an alternative
Rather than saving the item to favorites directly from the netflix plugin, I could sync those videos to my library (with default associated profile), then find the item in my library and add-to-favorites from that.

#### Development tips
I assume this can be done in the same way as is done when exporting to my library. But perhaps its not that simple.

#### Specific details
Using v1.16.1 of this plugin
I'm using latest CoreElec release, on -ng branch, with ODroid C4, but that is likely not important to this feature.
Let me know if you need more details of this feature request or of my set up.

#### Screenshots
None

**Comment by ashleysommer** [comment]
I've just noticed there _are some_ items in my favorites menu which do not ask for Profile when I play then. I think these tend to be items I've added to favorites from a much earlier version of the plugin (prior to v1.0.0).

I'll check my favorites.xml file to see if I can see any obvious differences between the items which work without asking for a profile, and those which do.

**Comment by ashleysommer** [comment]
Ok, super weird. I've confirmed there's no difference in favourites.xml between the items which ask my to select my profile, and those which do not. All do already have a `profile_guid` attached.  All have an action in the form `PlayMedia(&quot;plugin://plugin.video.netflix/play/movie/81035122/?profile_guid=2VNMNG7F65CDXOQMCMU6KBBZZQ&quot;)</favourite>`
All of them have the same `profile_guid`. Yet some ask me to choose my Profile, and some do not.

**Comment by CastagnaIT** [comment]
It is much more complex than what you think...

main problems:
1) kodi framework do not offer a method to distinguish where an "external call" comes from
2) to know if the call doesn't come from the addon himself, it is required to make work upnext addon and disable/enable some other features
3) the `profile_guid` argument is needed only to tell kodi database to not to mix the playcount/resume status of Listitems inside of addon lists (and only when sync of watched status if disabled). 

You can't think about save the GUID value permanently on a file or link, because will cause other problems, that not explain here.

An "external call" may come from different contexts:
-calls from kodi library
-calls from scripts
-calls from widgets
-calls from a file browser
-calls from other addons
-and so on...
the `Play From Here` context menu is broken because execute a video such as a script

the addon implement a generic workaround to understand if the call come externally, due to problem mentioned before.

The Kodi menu "Favourites" have a particular behaviour:

if there is a video like film (so on main Favourites folder) the addon recognize it like a external call
but
a folder like a "tv show" is executed as if apparently you were already browsing inside the add-on

**Comment by ashleysommer** [comment]
Thank you for confirming it is very complex and hard to understand, I thought I was going crazy.

I will try to train my wife to use Export to Library, and Save to My List, instead of Add to Favourites.

**Comment by CastagnaIT** [comment]
i suggest you to create kodi profiles for every family user,
then install NF on each Kodi profile
where every family component can have a own library

**Comment by ashleysommer** [comment]
Thanks for your suggestion. Unfortunately its not that simple. The NF account does not belong to us, its my wife's parents nf account. They shared with us their credentials and created one profile in their account for us to use on one device. So my wife, our children, and I all use the same NF profile. I don't think separate kodi profiles will help in that scenario, but it is a good suggestion.
I might just get my own Netflix account, then we can each have our own profile.

**Comment by ashleysommer** [comment]
Feel free to close this issue if you want to.

**Comment by CastagnaIT** [comment]
you got me thinking about solving the problem another way
if it works I'll have to make changes in every strm exported

basically, if it works:
- When you play from widgets or Preferences or "Play From Here" the video will be played with the last selected netflix profile
and should be better, due to current mixed behaviour, will be resolved

> if there is a video like film (so on main Favourites folder) the addon recognize it like a external call
> but
> a folder like a "tv show" is executed as if apparently you were already browsing inside the add-on

- When you play from kodi library (strm file) will be asked the profile to be use

for now only theory

**Comment by CastagnaIT** [comment]
With this PR https://github.com/CastagnaIT/plugin.video.netflix/pull/761 i have better managed the Favourites and Play From Here

it's not exactly what you asked for because you can't do it, but this is the new behaviour on next add-on release:

If you play from Favourites:
you will never be asked to select a profile, will be always used the last nf profile used to open the add-on

if you use Play From Here context menu:
now will work correctly in all situations
