### ISSUE TITLE
Change `IPC_TIMEOUT_SECS` from 20 seconds to 30 or more

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [CastagnaIT/plugin.video.netflix#781]
## Feature request
I'm submitting a proposal to ...
  - [ ] new feature
  - [x] change an existing feature

### Describe your request

**First and foremost, thank you for taking the time to develop this addon. I'm guessing it's used by a lot of people.**
I looked through the issues and found [https://github.com/CastagnaIT/plugin.video.netflix/issues/42#issuecomment-479348238](https://github.com/CastagnaIT/plugin.video.netflix/issues/42#issuecomment-479348238).
I followed that advice but it's no longer relevant so I have another solution.

The timeout for `IPC_TIMEOUT_SECS` in `\Kodi\addons\plugin.video.netflix\resources\lib\common\ipc.py` is currently 20 seconds and I almost always get an error popup about not being ready. Changing `IPC_TIMEOUT_SECS` to 30 seconds solves my issue. 

My request is to change `IPC_TIMEOUT_SECS` from 20 seconds to 30 seconds or more: LINE 25: IPC_TIMEOUT_SECS = 30

#### Describe the use case

I have `Kodi 18 x64` installed in `Windows 10 x64` and have the `CastagnaIT Repository for KODI 18.x LEIA - repository.castagnait-1.0.1.zip` repo installed.

All I usually use Kodi for is Netflix so I immediately open the Netflix plugin upon starting.

I'm in the US if that makes a difference and have 30 Mbps internet.

#### Describe an alternative

Alternative is to just sit there and wait about 10 seconds to give it time to connect. That's fine but not really ideal...

#### Development tips

My request is to change `IPC_TIMEOUT_SECS` from 20 seconds to 30 seconds or more: LINE 25: IPC_TIMEOUT_SECS = 30

**Comment by CastagnaIT** [comment]
Raising IPC timeout is not the panacea to all problems

Most of the times the problem is due to other:
1) problems with unstable networks
2) the current AddonSignals BUG. That also if there are 20 seconds set, the timeout is lowered to 7 seconds
the fix is not yet released: https://github.com/CastagnaIT/plugin.video.netflix/issues/716
3) too slow hdd storage or CPU under too much work at that time
4) an error raised in web request

In addition, in version 1.7.0 the internal loading of the data of my list that was the cause of take too long time (and  so cause of raise timeout) has been highly optimized in speed. The loading times are reduced about three times.

This means that something is not working very well in your situation

randomly shooting at other Issue threads makes no sense

**Comment by xCONFLiCTiONx** [comment]
Next time just say that you  have a fix on the way and remove the attitude. I'll see my way out.

**Comment by CastagnaIT** [comment]
The original value was 10 seconds, a value that has never caused trouble from oldest add-on versions,
has been raised to 20 seconds only in the recent versions, to allow possible mechanical HDDs or very slow MMC to process data

i have add IPC_TIMEOUT_SECS to make easier to user customize the timeout for this rare specific case of users
but this doesn't mean the value has to be raised for the whole community
