### ISSUE TITLE
firestick that plays 1080p just fine,new firetvcube 2019 will not play higher than 540p

### ISSUE THREAD

**Issue by neogeo71** [CastagnaIT/plugin.video.netflix#928]
i have a firestick that plays 1080p just fine,new firetvcube 2019 will not play higher than 540p.

I tried inputting my esn from netflix and same result

I installed the material terminal and ran getprop and see the output but there is no way to email from firetv. I cannot find a working email app. any ideas how I can save this terminal output to get it to you to review?

i tried getprop >info.txt but it says it is read only and cannot write the file.

please advise? I really would like to get your plugin working. I think it is a cube specific issue as I found one other user on reddit with same issues.

Thank you in advance for your time and attention to this matter.

**Comment by CastagnaIT** [comment]
I need you provide specified info otherwise I can not help

mandatory is a Debug Log follow all the steps explained in the Readme
but take the log only after you have done `Reset ESN` from expert setting

Follow step 1 and 3 of `Video Stream only at 540P (SD) on Android device`:
https://github.com/CastagnaIT/plugin.video.netflix/wiki/FAQ-%28Audio%2C-Video%2C-Subtitle%2C-Other%29#video-stream-only-at-540p-sd-on-android-device

and so attach/report all required info

**Comment by neogeo71** [comment]
This is my issue:
1) Install "Material Terminal" app or similar terminal app
2) Open the app, in the black screen write getprop so a long list appears
3) Open the options then select "Send to e-mail". (you can send the info to yourself and attach everything as a text file or if you prefer send directly to this GitHub e-mail)

I cannot do step 3 on the FireTV cube. How do I get this output off the FireTV to send to you?

**Comment by CastagnaIT** [comment]
alternative are:
1. try to connect a usb/bluetooth mouse
2. install TeamViewer to firecube and your phone, then control your firecube from the phone, in order to open the "material terminal" options
3. not easy alternative, use ADB via IP to control the shell from a computer, explain how to here require lot time, if you want try this way look from the web

**Comment by CastagnaIT** [comment]
closed due to inactivity
